### ISSUE TITLE
Cannot authorize on GrapheneOS

### ISSUE THREAD

**Issue by rekesz4** [michaldrabik/showly-2.0#154]
Hi,

I've been using Showly on another phone for a while and I love it. I'm switching to a Pixel 4A with GrapheneOS, but I cannot authenticate on trakt.tv. After I click on "trakt.tv authorization" it opens the login page in a browser, but hangs when I press Sign in. If I reload the page it logs me into Trakt.tv, but I cannot get to the page where I can authorize Showly to use my trakt.tv account. Tried in Vanadium and Bromite browsers.

I logged out on my other phone and was able to log back in easily on that one.

If you need any further info please let me know, I'd like to keep using your app.

**Comment by michaldrabik** [comment]
Hi thanks for writing. Ill try to help. Have you tried Chrome browser or Firefox? Try killing all the apps and browsers and then trying again. If that does not help could you make a screen recording showing whole process? 

Regards

**Comment by rekesz4** [comment]
Hey man, I was able to sign in with Firefox for Android. Maybe the problem only occurs with Chromium-based browsers? Anyway, this was a quick fix, sorry for taking your time with such a stupid solution :D

**Comment by michaldrabik** [comment]
That's a good news. Perhaps these other browsers have some more strict security options that block website (Trak.tv) from calling custom URI which is required by Showly app to come back and continue login flow. 

If this is fine I could share you an updated APK file with a fix that might solve this and you can give it a try on Vanadium. Unfortunatly I do not own any GraphenOS device.

**Comment by rekesz4** [comment]
Sure, I'd be glad to help out! Can you share it through github or do you need an email address?

**Comment by michaldrabik** [comment]
@rekesz4 
The file is below. You can give it a try but it's a shot in the dark - might work might not. Should install as normal update.

[app-release.zip](https://github.com/michaldrabik/showly-2.0/files/5578551/app-release.zip)

**Comment by rekesz4** [comment]
It's showing "showly2trakt.tv’s server IP address could not be found", not sure if it's trying to connect to the correct site now.

**Comment by michaldrabik** [comment]
@rekesz4 
After you enter your login credentials in the browser?

**Comment by rekesz4** [comment]
Before, it doesn't even load the login page. I go into settings, click on "Trak.tv Authorization" and the browser opens this: https://showly2trakt.tv/?code=71ebd375c0b14a89fc0f062b4cd2e3c1da04e919eb0bc144d23529ea999ade94

Immediately saying "This site can't be reached, showly2trakt.tv’s server IP address could not be found".

**Comment by michaldrabik** [comment]
Ok so I guess somehow these browsers does not trigger other apps intents. The link you pasted is a special link that should trigger Showly and send it the special code to continue with authorization (you are already logged in to Trakt so the credentials screen is skipped)

Dont really know why. Perheps there are some settings that block this behaviour.

**Comment by rekesz4** [comment]
Yeah I guess it might be due to heavier sandboxing. Anyway, it works with Firefox :) Thanks for the support!
