### ISSUE TITLE
[Not an Issue] Need some explainations

### ISSUE THREAD

**Issue by esQmo** [michaldrabik/showly-2.0#166]
Hello, can you explain what is the logic behind this code from MainRateAppCase (com.michaldrabik.showly2.ui.main.cases). 
I need to implement somthing a bit similar, a logic to prompt a notification whenever the app is updated. I need to notification to show each time the app is updated then the user will have to either dismiss the notification (will be shown again in next update) or delay it for a week.

**Comment by michaldrabik** [comment]
Hi, no problem.
The idea was to prompt user for a review 3 times at maximum:

1st attempt is made after after 10 days
2nd after another 10 days
and the last one is made after 14 days.

After this I never bother the user anymore. If the user completes the review `finalize()` is called to never show notification again.

**Comment by esQmo** [comment]
Oh thanks for the explaination. However, I'm a bit struggling to adapt the logic to my case:

- At start up, the app check from a remote URL the last version which is online, then compares with the actual app version from BuildConfig.VersionCode 
- And if the actual version is less than the remote verson, prompt user to install.
- The user is now presented with a dialog that has 3 buttons: Update now, remind later (7 days) and Cancel (update)
- When user chooses Cancel, the dialog is dismissed and will not appear anymore till next update (actual version < remote version code)
- If user chooses Remind later, the update should be shown after 7 day
- if the user delayes it again, show the dialog after 7 days again

Can you help me on this? or if it is out of the scope of this section. 
Thank you

**Comment by michaldrabik** [comment]
I think this case is a bit different but nothing seems hard in this.

Basically it seems like you need to save 2 values (in SharedPreferenced for example):
- last user decision (UPDATE, SKIP_VERSION, LATER)
- user decision timestamp

During the startup you should always run a function that will check last user decision. If it is LATER check current time and last user decision timestamp time difference is greater than 7 days. If it is SKIP_VERSION, make a remote call and check actual version. If it is UPDATE check if BuildConfig version is same as actual version (this would mean that user has actually completed an update)

**Comment by michaldrabik** [comment]
Also You might not be aware that there is an official Google API for this: https://developer.android.com/guide/playcore/in-app-updates

Might be useful unless you want your own custom solution.

**Comment by esQmo** [comment]
Thanks for the reply. Well I'm aware of that library but last time I tried didn't work. Maybbe a bad implementation or something. Thanks for your help
