### ISSUE TITLE
Shows with no seen episodes doesn't appear in my collection

### ISSUE THREAD

**Issue by enrikotero** [michaldrabik/showly-2.0#167]
I added some shows in another app to my collection in trakt. If that show has any episode seen it is marked as "added to my shows" but if there's no episode seen it isn't. It's normal not to see this shows in the "progress" tab but I think they should appear in the "collection" tab, also the "added to my shows" tag should appear in the detail page of the show.

**Comment by michaldrabik** [comment]
Hi @enrikotero .
When you add your shows in the other app does it appear in the Progress section in the Trakt.tv website? 
Showly only synchronizes Progress and Watchlist list. As you can see Trakt.tv does not really support adding a show into "Progress" without marking any episode as watched.

Trakt.tv  "Collection" is not the same as Showly Collection tab (they say this section is for DVDs and physical copies like BlueRays). This is why I chose to sync only Progress as this makes sense to me.

Let me know if that makes sense or you have more doubts.

Regards,
Mike
