### ISSUE TITLE
Add option to schedule Trakt sync on the app start

### ISSUE THREAD

**Issue by michaldrabik** [michaldrabik/showly-2.0#257]

**Comment by tiagogaspar8** [comment]
I was looking for this too.
I use Kodi and it syncs the watch list with trakt, and when I open showly it is out of sync and I have to manually refresh ( I know you can make it sync from time to time but I don't want it to drain my battery.

Thanks for the amazing app really! Couldn't do it better!

**Comment by Arathonk** [comment]
Oh yes! I'm really hoping for this feature. It's one of the reasons I'm not fully over to Showly yet.

**Comment by michaldrabik** [comment]
Starting v3.7.0 the app allows to pull down main progress screen to start Trakt sync
