### ISSUE TITLE
Google Backup

### ISSUE THREAD

**Issue by michaldrabik** [michaldrabik/showly-2.0#26]
Add option to backup data with user's Google Drive account.

**Comment by Donkey-Doug** [comment]
What about people that do not like using cloud storage? I would prefer to save a file to my device's internal memory, like NewPipe does. NewPipe is also open source by the way, so you might want to check their implementation.

**Comment by ad0726** [comment]
Can we imagine to have Nextcloud or Owncloud backup or something else? To be able to backup data on some open source cloud.
Or a database export, in a first step?

**Comment by michaldrabik** [comment]
@ad0726 I'm leaning towards backup-to-file export option. 
User could then choose his own preferred way to store it. Google drive, email or anything else.

**Comment by isarrider** [comment]
Is there any news on export?

**Comment by snvoid** [comment]
Is there a way to export yet? I'm not sure how to do it. Thanks

**Comment by isarrider** [comment]
is there already a roadmap for this?
