### ISSUE TITLE
[BUG] Incorrect episodes appearing on progress

### ISSUE THREAD

**Issue by Generator** [michaldrabik/showly-2.0#293]
## Description 

Watched episodes or non existing episodes appears on progress

**Showly Progress:**
![Screenshot-2020-12-26-15-13-44](https://user-images.githubusercontent.com/44146/103154062-139dc680-478d-11eb-9d7d-18aa8402fca4.jpeg)

**Pennyworth (watched):**
![Screenshot-2020-12-26-15-01-32](https://user-images.githubusercontent.com/44146/103153958-60cd6880-478c-11eb-9847-9def15d50bbc.jpeg)

**The Island With Bear Grylls (non existing season):**
![Screenshot-2020-12-26-15-01-49](https://user-images.githubusercontent.com/44146/103153964-6a56d080-478c-11eb-901a-aef4d5b2fd5a.jpeg)

**Trakt.tv Progress:**
![Screenshot_2020-12-26 Dashboard(1)](https://user-images.githubusercontent.com/44146/103154017-c4579600-478c-11eb-8eae-6cec73e6a02d.png)

**Comment by michaldrabik** [comment]
Hi! Thank you for a detailed report.

Out of the top of my head I don't know what could cause this. I will try to investigate further as soon as I can.
At this moment you could try to reset a progress and see if that helps? Let's take Pennyworth for example.

Try going into details page then uncheck all the seasons (so everything is unwatched). Then remove the show from your collection (click 'Added to my shows'). After this you can add it again and mark all episodes as watched. Let me know if that changes anything.

Regards,
Mike

**Comment by Generator** [comment]
Try unchecking all episodes and recheck, on the show page shows the correct information, however on progress still shows the incorrect episode.  

**Correct 'Next Episode':**
![Screenshot-2020-12-27-21-30-17](https://user-images.githubusercontent.com/44146/103180169-239bd000-488b-11eb-941b-06553cc705d9.jpeg)

**Comment by michaldrabik** [comment]
@Generator Thanks. Did you remember to remove if from your shows after unchecking? If that does not help could you show me Details of that invalid episode?

It seems like an episode from another series got mixed up and I'd need to find out which.

Thanks

**Comment by Generator** [comment]
> Did you remember to remove if from your shows after unchecking?  

Could find that option on the app, i could remove from trakt.tv, but seem the issues is local not remote (trakt.tv).

> If that does not help could you show me Details of that invalid episode? 

![Screenshot-2020-12-27-21-38-55](https://user-images.githubusercontent.com/44146/103180269-3236b700-488c-11eb-9286-6f3c4926d0a9.jpeg)


Not a developer, but seems like the app pulled the info from the show when it was still TBA, then when got updated and mixed-up with new data.

Other apps like [Cathode](https://play.google.com/store/apps/details?id=net.simonvt.cathode) shows the correct information.

**Comment by michaldrabik** [comment]
@Generator Yup I agree thats some bug in the app. 

> Could find that option on the app, i could remove from trakt.tv, but seem the issues is local not remote (trakt.tv).
Just needs to click "Added To My Shows" after you uncheck all the episodes. Then click "Add to My Shows" again and update your progress.

If that does not help the only way at this moment seems to be clearing the app data (or simply reinstall) and import your Trakt.tv data again. This should fix it. If it does not let me know :)

Thanks

**Comment by Generator** [comment]
> Just needs to click "Added To My Shows" after you uncheck all the episodes. Then click "Add to My Shows" again and update your progress.  

Sometimes can't see the obvious! Only clicking on "Added To My Shows" and "Add to My Shows" fixed the incorrect information.
![Screenshot-2020-12-27-21-55-14](https://user-images.githubusercontent.com/44146/103180557-70cd7100-488e-11eb-90b6-769f94a259a3.jpeg)

**Comment by michaldrabik** [comment]
@Generator Cool. I'm still wondering how did that happen in the first place though as it should not.
If you ever see something like that again please leave a comment :)
