### ISSUE TITLE
JustWatch support

### ISSUE THREAD

**Issue by rodrigoswz** [michaldrabik/showly-2.0#296]
Please, add a button for search the show on JustWatch. In this way it is possible to quickly find the content on many streaming services.

It would be even better if this search was possible within Showly itself, but if not, just a button to access the show on JustWatch website already helps a lot.

**Comment by DurchEins** [comment]
I would appreciate this feature too

**Comment by michaldrabik** [comment]
Hi. As far as I know JustWatch does not provide their API for smaller "businesses".
I will contact them just to be sure.

 Without this the only option would be to redirect user from the app into the search website of JustWatch (+ another dialog to select country)

**Comment by rodrigoswz** [comment]
> Hi. As far as I know JustWatch does not provide their API for smaller "businesses".
> I will contact them just to be sure.
> 
> Without this the only option would be to redirect user from the app into the search website of JustWatch (+ another dialog to select country)

Hi! I understand, it's okay for me to redirect into website search, it would be a really great feature anyway.

About the dialog to select the country, maybe pre-defining it in the Showly settings would be interesting 😁

**Comment by michaldrabik** [comment]
JustWatch search link has been added to links menu for shows and movies. Region can be changed in the settings (US default). Will be rolling out soon.

**Comment by DurchEins** [comment]
Thanks for the integration! 
Two things: It would be cool if the links opened in Custom Chrome Tabs instead of the entire Chrome browser. And it would be cool if the linked icons got their own row because there are quite a few. :) For example under the current row (under reviews etc.).

**Comment by michaldrabik** [comment]
> Thanks for the integration!
> Two things: It would be cool if the links opened in Custom Chrome Tabs instead of the entire Chrome browser. And it would be cool if the linked icons got their own row because there are quite a few. :) For example under the current row (under reviews etc.).

Yep got Chrome Tabs in the back of my head. Current way was just pretty straightforward and fast to release so I started with that.
