### ISSUE TITLE
Add option to sort by user rating

### ISSUE THREAD

**Issue by Sonphil** [michaldrabik/showly-2.0#305]
At the moment, on the Collection page, I can sort my shows and my movies by rating. However, I would also like to sort them by my rating (`userRating`), so something like
```
USER_RATING -> movies.sortedByDescending { it.userRating }
```

**Comment by michaldrabik** [comment]
Yeah It probably makes sense. Just needs some more work to account user not being logged into Trakt or a failure while preloading ratings. I'll take a look.
