### ISSUE TITLE
"Brazil" as Justwatch Region redirects to an invalid link

### ISSUE THREAD

**Issue by rodrigoswz** [michaldrabik/showly-2.0#314]
First thanks for the quick update to include this feature!

There is a small problem that redirects the link incorrectly.
I realized that the pattern (US) has **search** word in the link. But the searches in the region of Brazil, this part of the link is translated, resulting in **busca** instead of _search_.

Example...

Currently does: https://www.justwatch.com/br/search?q=The%20Office

How it should do: https://www.justwatch.com/br/busca?q=The%20Office

**Comment by michaldrabik** [comment]
Confirmed. Will be updating that.
