### ISSUE TITLE
Hidden Shows aren't included in statistics

### ISSUE THREAD

**Issue by hyPnOtICDo0g** [michaldrabik/showly-2.0#344]
So there are a couple of shows I've dropped & I hide them on trakt so that they don't clutter my **Up next to watch** (on website homepage).  Showly doesn't sync them to device and in turn they don't appear in my stats. I had to unhide, sync, re-hide and move them to Archive to get them added to my stats. So is it possible to sync them directly to **Archive**? Also, I've toggled the Archived Statistics button.

**Comment by michaldrabik** [comment]
@hyPnOtICDo0g Hi. You are right. Currently Trakt.tv hidden shows are ignored during Showly Import. 

It's not possible to import straight into Archive because Archive is not meant to be mapped to Trakt hidden items. It's just unique to the app feature currently.

**Comment by hyPnOtICDo0g** [comment]
Hi! Thanks for replying. By unhide & re-hide I meant I did it on the website to clear the clutter (Again).
