### ISSUE TITLE
Improvements to Movies section under Collection

### ISSUE THREAD

**Issue by dewrano** [michaldrabik/showly-2.0#381]
Hi,

Thank you very much for Showly, it's a great app! I'd like to suggest some possible improvements to the Movies section under the Collection tab. 

Can the "Returning & Upcoming" (maybe just "Upcoming" for movies) and "Finished" sections be added for movies under the Collection tab, similar to the Shows section? With this change, a "My Movies Sections" (like the "My Shows Section") setting under "General & UX" could be added. It would also be great to have the option to disable the "Recently Added" section for movies (same option exists for shows). In my case, it fills a lot of the screen and it doesn't add too much value for me, so the customization would be great.

I hope you don't mind, but I also have a question which isn't related to the text above. How long does it take for the updates to reach the Google Play Store? I'm still on v2.4.0 (254) even though v2.5.0 (258) has been released.

Thank you!

**Comment by michaldrabik** [comment]
@dewrano Hi!

> Can the "Returning & Upcoming" (maybe just "Upcoming" for movies) and "Finished" sections be added for movies under the Collection tab, similar to the Shows section?

I think for Movies this would not have much sense at all. For movies there are only 2 state. Either you have or have not seen it yet. The ones taht you have seen go into "My Movies" while those that you have not are in Watchlist. I may consider adding an "Upcoming" badge for Watchlist movies that have not been aired yet (so basically those in Calendar section)

> It would also be great to have the option to disable the "Recently Added" section for movies (same option exists for shows). In my case, it fills a lot of the screen and it doesn't add too much value for me, so the customization would be great.

The setting will be added in the next update.

> I hope you don't mind, but I also have a question which isn't related to the text above. How long does it take for the updates to reach the Google Play Store? I'm still on v2.4.0 (254) even though v2.5.0 (258) has been released.

Those are just Github tags so don't rely on them as a pure indicator that new version is pushed to PlayStore. I'm using them internally to mark my progress. However if new version appears in Github you can be quite certain that it's coming to PlayStore "soon" :)

**Comment by dewrano** [comment]
Thank you! I agree with your points. I'll be waiting for the update to land in Play Store. Would you consider adding an Auto Updater in the app itself?

By the way, it would be a good idea to link to your ShowlyApp Twitter link on showlyapp.com :-)

**Comment by michaldrabik** [comment]
Yeah this landing page will be remade and I will add it then. Thanks :)
I also want to include: https://developer.android.com/guide/playcore/in-app-updates
sooner or later.
