### ISSUE TITLE
Is the In-app update feature available yet?

### ISSUE THREAD

**Issue by esQmo** [michaldrabik/showly-2.0#390]
hey @michaldrabik, just noticed one of your commit is mentioning the In App Update feature from Play Core. Tried to follow and adapt what you did, but couldn't make it work, or may be it is not working yet or bad implementation from my side. Does it work already for Showly?

**Comment by michaldrabik** [comment]
I rolled it out with latest version so it will effectively start to work with next update.

Make sure you are testing it via Play Store. So you must make your test releases via Internal Test Track.
Also when checking out my implementation notice that I'm using a 3 days threshold time (in-app update dialog will not be triggered if PlayStore manages to update the app automatically in the background or user does this manually)
