### ISSUE TITLE
Search should be more consistent with TMDB concerning shows/movies and their languages.

### ISSUE THREAD

**Issue by Brokray** [michaldrabik/showly-2.0#396]
Hello there, 

I just observed something on your app : I use it in English even though I am a native French speaker.

If I search a French show such as "Dix pour cent" on the app no result will be found. 
However the [same search on the English version of TMDB ](https://www.themoviedb.org/search?query=Dix+pour+cent) website will be successful.

I would expect the same result on the app. 
Did I miss something?

Cheers!

**Comment by michaldrabik** [comment]
@Brokray Hi.

Showly is currently using Trakt API as a main search engine.

It seems that this show's title is simply not translated into Dix Pour Cent currently:
https://trakt.tv/search?query=Dix+pour+cent

I can find it under Appelez Mon Agent though:
https://trakt.tv/search?query=appelez+mon+agent

**Comment by Brokray** [comment]
Thank you for your explanation. I don't know why I thought it used TMDB API, my bad.

Still, this is interesting...     
Trakt uses the french canadian title of the show while the original french name in is indeed "Dix pour cent".

I might bring that up to **Trakt** as it also happens with other French shows and it feels kind of wrong to not be able to find a show by it's original name.

Thanks you for your quick answer and your amazing app,
Cheers.

**Comment by michaldrabik** [comment]
No problem. TMDB is used only with images and actors currently. Rest is all Trakt. They do however started full transition to TMDB as well recently: https://blog.trakt.tv/tmdb-transition-ef3d19a5cf24
