### ISSUE TITLE
Add Sort by Release date to Movies

### ISSUE THREAD

**Issue by ibeltran** [michaldrabik/showly-2.0#397]
It would be nice to be able to sort by Release date (both Most recent and Latest), and leaving the ones without Release date at the end.

**Comment by michaldrabik** [comment]
Hi. Which section of the app are you referring to?

**Comment by ibeltran** [comment]
Progress - Movies.

I can only sort by Title and Recently added.

**Comment by michaldrabik** [comment]
Yea this could be added. I think I already had a task for that but can't find it now.

**Comment by michaldrabik** [comment]
Added.
