### ISSUE TITLE
VPN issue

### ISSUE THREAD

**Issue by isarrider** [michaldrabik/showly-2.0#402]
When I am in a VPN, it wont connect...
Mail, Whatsapp and so on work fine.
I have one other app that checks only for Wifi or mobile,
but doenst allow other was to connect...
Maybe loosen that restriction?

**Comment by michaldrabik** [comment]
Hi.

There are no special restrictions for VPN. I'm also behind the VPN quite often and there are no problems.
Also what to do you mean by "it wont connect"? Are you able to open www.trakt.tv website while behind VPN?

Regards

**Comment by isarrider** [comment]
Hi,

no I am not...
I think it is connected to that:
https://developer.android.com/training/basics/network-ops/managing...

**Comment by michaldrabik** [comment]
@isarrider If you are unable to open www.trakt.tv in your browser while connected to VPN then it's not an app problem but something else - perhaps something with the configuration?

**Comment by isarrider** [comment]
Ah, I misunderstood...
Yes, of course, chrome works fine...

**Comment by michaldrabik** [comment]
Okay. So just to be clear when you are connected to VPN the app won't load anyhing? Does it throw an error or something? Do you have any screenshot you can share?

Is this VPN one of the public services that I could test out myself (like NordVPN)?

**Comment by isarrider** [comment]
>Nope, no public VPN...
Looks like this:

![Screenshot_20210203-113203_Showly 20](https://user-images.githubusercontent.com/6953309/106736623-fb378c00-6615-11eb-9a20-f1be3e2de5e0.png)

**Comment by michaldrabik** [comment]
Okay - if you open details of a show that you have never opened before does it load fine? Can you see seasons data there?

**Comment by isarrider** [comment]
it loads.... But for example the quick progress doesnt load anything...
Also, it says seasons not availible after clicking on a show...

**Comment by michaldrabik** [comment]
I'll try to search logs. Could you tell me what is your phone model?

**Comment by isarrider** [comment]
S9+

**Comment by michaldrabik** [comment]
Can't see anything but If you would like to help me investigate this please drop me an email at showlyapp@gmail.com
I can build a special APK for you that will show all the errors in the app and we could see whats wrong exactly.

Regards

**Comment by isarrider** [comment]
I just dropped u an email...

**Comment by isarrider** [comment]
and I saw sth, I think issue #101 is very related...

**Comment by isarrider** [comment]
![Screenshot_20210204-104217_Showly 20](https://user-images.githubusercontent.com/6953309/106875046-85dfc000-66d6-11eb-8ca2-e58fe6dd482b.png)
Same with manual refresh, but the images get loaded...

**Comment by isarrider** [comment]
not the seasons...
![Screenshot_20210204-104426_Showly 20](https://user-images.githubusercontent.com/6953309/106875147-a0b23480-66d6-11eb-9a57-a77861aa7183.png)

**Comment by isarrider** [comment]
quick progress doesnt also work then, prob related to seasons not loading...
![Screenshot_20210204-104421_Showly 20](https://user-images.githubusercontent.com/6953309/106875231-bb84a900-66d6-11eb-9c88-23c1fe56de48.png)

**Comment by michaldrabik** [comment]
The issue was related to proper VPN network detection. Fixed and waiting for release.

**Comment by isarrider** [comment]
THank you very much... awesome dev!
