### ISSUE TITLE
Rate App dialog's actions are truncated when their text labels are too long

### ISSUE THREAD

**Issue by Sonphil** [michaldrabik/showly-2.0#418]
![image](https://user-images.githubusercontent.com/22182973/107864975-16817300-6e30-11eb-9e3a-9d9da31f4d36.png)

The actions should be stacked when their text labels are too long.

**Comment by michaldrabik** [comment]
Thanks for spotting, will fix but starting next update I'll begin testing Review flow that does not use this dialog (as Google advises).
