### ISSUE TITLE
Rate App dialog's positive action doesn't appear to work

### ISSUE THREAD

**Issue by Sonphil** [michaldrabik/showly-2.0#419]
When I opened the app, it showed me the rate app dialog. However, nothing happened when I clicked on the "yes" button. 

Moreover, according to [Google Play In-App Review API documentation](https://developer.android.com/guide/playcore/in-app-review), the app should not have a call-to-action option (such as a button) to trigger the API.

**Comment by michaldrabik** [comment]
Yep it is a guideline not restriction though. I'm not sure If I agree with this but I'll start testing this flow starting with next update.

**Comment by Sonphil** [comment]
@michaldrabik Yeah, for me, it was a little bit weird because nothing happened when I clicked on the "yes" button.
