### ISSUE TITLE
Cant unselect episodes (usually in the specials)

### ISSUE THREAD

**Issue by isarrider** [michaldrabik/showly-2.0#421]
Hi...

I cant unselect some episodes... (usually in the special section)...

**Comment by isarrider** [comment]
![01](https://user-images.githubusercontent.com/6953309/107944686-d258b480-6f8e-11eb-99e9-88de9bda1ea1.png)

**Comment by isarrider** [comment]
![02](https://user-images.githubusercontent.com/6953309/107944697-d84e9580-6f8e-11eb-87a6-4e653ff5e121.png)

**Comment by michaldrabik** [comment]
@isarrider Thanks. It's happening because they get imported from Trakt.tv with watched state already. I will need to handle this in coming updates. For now I think the only option is to mark them as watched in Trakt website and import.

**Comment by isarrider** [comment]
Hi... Forgot to mention, I have not enabled sync to trakt.tv and never had...
(thats why I asked here: https://github.com/michaldrabik/showly-2.0/issues/26) for the export / import functionality... ;)

**Comment by michaldrabik** [comment]
@isarrider OH, ok then. Have you ever marked this special episode by yourself or was like this out of nowhere?

**Comment by isarrider** [comment]
I def. used with some shows the "Quick progress" feature...
I never marked them one by one...
If it was with a show out of nowhere I cannot say for sure...

**Comment by michaldrabik** [comment]
Thanks. I think I might see a small bug... Next update I will also unlock all Special epiosdes marking so you will be able to get rid of it.

**Comment by isarrider** [comment]
awesome... gracias...

**Comment by michaldrabik** [comment]
Related to #422 
There will now be an option to unlock episodes and mark/unmark them no matter of date.
