### ISSUE TITLE
Let mark episodes as watched even when they haven't aired yet

### ISSUE THREAD

**Issue by seldon1000** [michaldrabik/showly-2.0#422]
Sometimes, episodes airs differently depending on your nation and you end up watching them before their "official" release date. Showly should let users mark episodes as watched whenever they want.

Example:
![Screenshot_20210216-085244_Showly_2 0](https://user-images.githubusercontent.com/55358113/108037470-f4f3d780-7039-11eb-806b-31574843db20.png)
![Screenshot_20210216-085250_Showly_2 0](https://user-images.githubusercontent.com/55358113/108037485-fa512200-7039-11eb-8a36-013f40a61e1e.png)

I have already watched those last four episodes. I marked them as watched on Trak.tv website but being able to do it in Showly would be convenient.

**Comment by michaldrabik** [comment]
I've been getting some feedback on that previously and I think it's true.
I will add an option to unlock these episodes in season view if someone wants to mark them prematurely.

**Comment by seldon1000** [comment]
That would be perfect, thanks!

**Comment by michaldrabik** [comment]
There now will be an option to unlock future episodes in season view and mark them if user wishes so.

https://user-images.githubusercontent.com/11537045/108215809-06200f80-7132-11eb-8dc9-0fb07476afc4.mp4

**Comment by seldon1000** [comment]
Just another little suggestion. If I've already marked the episode as watched, I shouldn't be notified when it's out.

**Comment by michaldrabik** [comment]
It shouldn't. I'll check it maybe theres a bug.
