### ISSUE TITLE
Swipe through episodes

### ISSUE THREAD

**Issue by Mannivu** [michaldrabik/showly-2.0#428]
It would be really nice to have the ability to swipe through the episodes. Some other apps are able to do that: this is a video record from the Android app [Series Mate](https://play.google.com/store/apps/details?id=com.tgomews.seriesmate&hl=en_US&gl=US):

https://user-images.githubusercontent.com/42747216/108592755-bf1f5d80-736f-11eb-807c-5cff8ba8a6fc.mp4

Having the episode open up, the user can swipe to the previous or the next episode without exiting the episode view. In Shwoly this feature is missing: the episode view is just a partial window and the user can't swipe through episodes. I like the partial window style, but I'd like to see the swipe feature implemented.

**Comment by michaldrabik** [comment]
Added season episodes tabs for a quicker selection:
![image](https://user-images.githubusercontent.com/11537045/109546537-a2e79300-7aca-11eb-938c-901ed6d25ef8.png)

**Comment by Mannivu** [comment]
Great! Thank you!
