### ISSUE TITLE
Inaccurate Trakt.tv import

### ISSUE THREAD

**Issue by Relwi** [michaldrabik/Showly-2.0#43]
When I select the option "Import from Trakt.tv" to Showly, the import process is correct, but I have in my Trakt.tv profile, movies and shows in collections and doesn't appear in the app, and backwards, i had films and shows in collections, but now i haven't, and that shows still appear in the app.

**Comment by michaldrabik** [comment]
Hi @Relwi 

Movies are currently not supported in the app.
Trakt.tv Import is now only importing "Watchlist" and not custom collections as they are not represented in Showly in any way.

**Comment by Relwi** [comment]
Okay, thank you!
