### ISSUE TITLE
Strange icon

### ISSUE THREAD

**Issue by Donkey-Doug** [michaldrabik/showly-2.0#432]
Hi, for shapes other than circle the app icon has a visible dot. See screenshots below.

![Round](https://user-images.githubusercontent.com/50382414/108611787-5ae9b180-73e2-11eb-910c-3fac01ff43e0.png)
![Rounded circle](https://user-images.githubusercontent.com/50382414/108611790-60df9280-73e2-11eb-8a74-b34ae9f5d78e.png)
![Teardrop](https://user-images.githubusercontent.com/50382414/108611793-650bb000-73e2-11eb-8272-36fbddc4b21d.png)
![Square](https://user-images.githubusercontent.com/50382414/108611794-689f3700-73e2-11eb-870d-01d092142902.png)

**Comment by michaldrabik** [comment]
@Donkey-Doug Are these screenshots from your device? If so what's the device and which Android version is it? Thanks

**Comment by Donkey-Doug** [comment]
Yes, these are screenshots.

Device: Xiaomi Mi 9T Pro
OS: LineageOS 17.1 (android 10)

**Comment by michaldrabik** [comment]
Added some adaptive icon handling which should probably fix this next update.

**Comment by Donkey-Doug** [comment]
Final update fixed the issue
