### ISSUE TITLE
Optional items horizontal scrolling layout movies/shows main listing

### ISSUE THREAD

**Issue by esQmo** [michaldrabik/showly-2.0#434]
Would adding an optional item diplaying as horizontal scrolling and sectioned by genre, etc, would that go far from the scope of this app that focuses on simplicity?

I thought it would be awesome to let users display movies and shows in horitontal and categorized by genre or year, or whatever, like most movie apps do.
Note that there is no problem the way it is now of course.

Cheers

**Comment by michaldrabik** [comment]
Keeping topic in "Discussions" https://github.com/michaldrabik/showly-2.0/discussions/430?ts=2
