### ISSUE TITLE
Ability to display/edit custom trakt list

### ISSUE THREAD

**Issue by elvis0288** [michaldrabik/showly-2.0#435]
I would like to be able to modify and view my custom lists like top TV shows or horror shows to watch and so on

**Comment by michaldrabik** [comment]
Custom lists will be next big thing I'll be working on. I think there should be task for that somewhere here already.

**Comment by elvis0288** [comment]
thank you, i will contribute on this project on my free time.. i have some ideas for the statistics i would like to include.. you know fun stats

**Comment by michaldrabik** [comment]
Sure, people usually post ideas here: https://github.com/michaldrabik/showly-2.0/discussions/categories/ideas

**Comment by elvis0288** [comment]
well i was not thinking about adding ideas but to develop them. i am a developer.. have not work on android for the last 2 years but i will relearn.. i really like this.. question if i make a change and i want to push it then what? you will review it and approve it? what is the process you are using?

**Comment by michaldrabik** [comment]
If you feel like it then sure. You could simply create a PR with short description whats it about and what it changes. I can review it and apply my own fixes / comment.
