### ISSUE TITLE
feature request: display the most recent unwatched episode

### ISSUE THREAD

**Issue by rbarbazz** [michaldrabik/showly-2.0#436]
Hi,

first of all, thank you for the app, I have started using it recently and I really enjoy it!

It would be great if, on the "progress" view, the next unwatched episode would be the most recent one.

Let's say you've picked up a show on season 5, currently, the app will always display S01E01 as the next episode to be watched. On trakt.tv, it would display the next episode in season 5.
If not the default behaviour, maybe it could be an option?

Please find the screenshots below to illustrate.

Showly:
![progress_screen](https://user-images.githubusercontent.com/42906704/108932694-a4aee380-75fe-11eb-86fc-d11e7fa9b2b0.jpg)
![show_screen](https://user-images.githubusercontent.com/42906704/108932697-a5e01080-75fe-11eb-9a91-9f9546c944e2.jpg)

Trakt:
![Screen Shot 2021-02-23 at 17 44 11](https://user-images.githubusercontent.com/42906704/108932760-bf815800-75fe-11eb-85ff-6718423f3f2d.png)

**Comment by michaldrabik** [comment]
It took some time but this will be added and released with the upcoming update.
