### ISSUE TITLE
When a movie is on the watchlist need to step to set it as watched 

### ISSUE THREAD

**Issue by elvis0288** [michaldrabik/showly-2.0#440]
Hello so when I movie is on the watchlist but instead of going through the wachtlist you search for it and open the main movie screen, there is not a way to set it as watched unless I first removed it from the watchlist and then when the add to movies/see laters shows buttons appears, then you can set it as watched. I think we should have 2 buttons there always one to watch and one to watch list

![Screenshot_20210228-004445_Showly 20](https://user-images.githubusercontent.com/7027367/109404524-d6a5aa00-795e-11eb-891b-76a7fe1159cc.jpg)

**Comment by michaldrabik** [comment]
This will be added in the upcoming update.
