### ISSUE TITLE
Sort by users' rate in Collection 

### ISSUE THREAD

**Issue by mertbakir** [michaldrabik/showly-2.0#441]
It would be really good to be able to sort by my own rating beside current options.

Also, filtering the collection by genre would be nice.

![SmartSelect_20210228-180715_Showly 20.jpg](https://user-images.githubusercontent.com/43188411/109423259-d1dd0680-79ef-11eb-83fd-99c0f15ff1c5.jpg)

**Comment by michaldrabik** [comment]
Hi, thanks. i already have this logged in #305 - wating to be done.

By the way is this device a tablet? I'll probably need to add some alterante UI for tablets in the future.

**Comment by mertbakir** [comment]
Yes, it's a tablet, 11". Existing UI is more than enough for me, still I can test and give feedback if you need help on that.

**Comment by michaldrabik** [comment]
Thanks, no need for now. I'll keep that in mind for future.
Tablets are (unfortunately) not a priority for me now because there are like < 1% people using Showly with tablets right now.

**Comment by mertbakir** [comment]
Makes sense. Also the current UI is pretty good in my opinion. I was using TV Time before, Showly is better in terms of speed and look.
