### ISSUE TITLE
Search feature needs improvement

### ISSUE THREAD

**Issue by mertbakir** [michaldrabik/showly-2.0#442]
My experience with search function is really bad. 

1. I don't know how it sorts the results but it should be top rated, most clicked (popular), or even better add an option to sort.

2. We should be able to filter by year, e.g. `movie.name y: 2019`. 

3. We should be able to use the cast (director, actor, actresss) as keywords.

4. More filter options even without movie name (director: x, genre: drama, sort-by: rating)

5. It should exclude special characters e.g. (dots, apostrophe, colon)

6. Search should give similar results. It looks for exact matches. e.g. when I type 'movr', it should return results for 'move'

**Comment by michaldrabik** [comment]
Hi, thanks. Right now I'm working on a custom lists support. When I'm done I'll be revisiting search screen for updates.

Some of the suggestions are doable and some are not due to Trakt.tv API limitations on search.

**Comment by elbowz** [comment]
I hope to dirt the issue report...

Maybe related, and simple add, could be display Film/serie **Year** (and **Director**?) in the list result. Also Director in the movie sheet...

This could be very useful when there is a lot of film with the same name (eg. "Limbo"), and the poster don't help to discriminate between the movies
