### ISSUE TITLE
found a bug when changes added movies/shows on trakt

### ISSUE THREAD

**Issue by elvis0288** [michaldrabik/showly-2.0#447]
Hello,

so i found a bug in which lets say we add a movie/show that we did not have before directly on trakt and when refreshing the data in showly it will sync correctly and now it will show in showly as added to watchlist. the problem is that if now i want to go ahead and remove that movie from the watchlist on trakt and then refresh showly then instead of removing that movie from my watchlist in showly, it will actually set it to my watchlist on trakt.

for example i have justice league set in my watchlist in both places (showly and trakt) now i go into trakt and remove it from my list refresh page everything is now good but if i go into showly (or wait for showly automatically import/export schedule) it will set the movie back to my watchlist in trakt instead of removing it from showly

was i clear with the explanation?

Thanks!

**Comment by elvis0288** [comment]
i guess after reading the instructions on the trakt.tv sync it looks like you are not deleting the data from collection if we remove it from trakt you will only add missing data, so in this case i guess i cannot use trakt at all to remove movies or tv shows i do not want to watch anymore? i will have to use the app and i will have to remove the export sync so it will not set to true back again in trakt?

**Comment by michaldrabik** [comment]
@elvis0288 Hi.

When the app imports watchlist from Trakt it receives a list of movies (for example). Let's say you have a movie in your Showly watchlist that is not present in the Trakt list. The app can't possibly now if you have actually removed it from your Trakt watchlist (so we should also remove it from the app) or has the movie never actually been there. So

Showly watchlist:
Movie 1 
Movie 2
Movie 3

Now we run the Trakt import.
Trakt Watchlist returns: 
Movie 1
Movie 2

We do not know if Movie 3 should be removed.
This is why Sync works in a "non hostile" way. To avoid removing collection items by accident.

**Comment by michaldrabik** [comment]
@elvis0288 You can however enable "Trakt Quick Remove" option in settings. With this switched on whenever you remove an item from Watchlist or Progress the app will ask you if you want to also remove it from your Trakt account and you can decide.

**Comment by elvis0288** [comment]
thank you for the quick response. yes i have this checked and i guess from now on i need to make sure to remove them from the app instead of trakt or they will go back into it.. if i will do a huge change into my trakt is there a way to clear the data i have in showly and clear all from it to do a clean refresh?

**Comment by elvis0288** [comment]
can an option be added into that section where the "trakt quick remove" is to allow deletion of movies from watchlist if not on trakt... this way i guess in your example above if movie 3 is not on trakt then we will also delete it from showly..

**Comment by michaldrabik** [comment]
> if i will do a huge change into my trakt is there a way to clear the data i have in showly and clear all from it to do a clean refresh?

The easiest way for now is to go into Showly settings in the Android system and use Clear Data and Caches option. This will bring the app back to "after install" state. I may add clear database option in the app itself though.

> can an option be added into that section where the "trakt quick remove" is to allow deletion of movies from watchlist if not on trakt... this way i guess in your example above if movie 3 is not on trakt then we will also delete it from showly..

I feel like there might be too many different Trakt sync options that could bring more confusion. Would also need to add same switches for Progress etc. (also custom lists that I'm working on). I will reconsider this if more people start asking about it.

Hope you will enjoy the app anyway :)

**Comment by elvis0288** [comment]
oh i really enjoy the app not doubts about that.. thank you for your work. i will just remember i need to make changes in the app instead of directly on trakt lol.

**Comment by michaldrabik** [comment]
Note that when you are in Trakt and mark movie that is in Watchlist as watched it will be removed from Watchlist automatically. This will also be reflected in the app.

**Comment by elvis0288** [comment]
yes that part works perfectly this is more about when removing movies/shows from the watchlist. so i guess this will also apply with the custom lists. if i remove a movie/show from my custom lists in trakt then it will still show on showly as if it was on that list right? so specifically when removing from lists i will need to do it from the app and then click yes when ask if i want to also remove it from trakt

**Comment by michaldrabik** [comment]
It's a work in progress I will see. Probably yes to maintain consistency but I will see about that.
