### ISSUE TITLE
Showly syncs the wrong show

### ISSUE THREAD

**Issue by carlocastoldi** [michaldrabik/showly-2.0#452]
There is not much else I can add to the title. I have sync enabled everyday between Showly and Trakt (both ways).
In neither platforms I have this "[Pride](https://trakt.tv/shows/pride/seasons/1/episodes/1)" show in my history, and yet—on every sync—it pops up a new play on the 16th of January.

On that day I probably (can't say for sure) watched this episode: https://trakt.tv/shows/sanpa-sins-of-the-savior-2020/seasons/1/episodes/1 (SanPa 1x01).

At the time I must have manually synced it with a trakt page that it is no longer available (maybe in favour of the above-linked page). I can say it because I am sure that i synced SanPa at the time, and yet it is no longer in my trakt history.
In Showly, after I forced a sync with trakt, I can see there still is SanPa in my history but clicking on it gives me an error while trying to load the page.

**Comment by michaldrabik** [comment]
@carlocastoldi  Hi. Let's try to see what's going on there.

First of all please clarify if "pops up on every sync" means it appears in Trakt.tv web or in the app? Thanks

**Comment by carlocastoldi** [comment]
Thanks for the quick reply! ^^

Yeah, sorry for the bad term. By "popping up" I meant that it appears in Trakt.tv web in my history

**Comment by michaldrabik** [comment]
My first idea is to simply start with a clean slate. If this is possible for you of course. Make sure that your Trakt.tv Web is set as you want it and then simply reinstall Showly or clear data and try syncing from there.

**Comment by carlocastoldi** [comment]
Alright. That did it, yep.

Just remember that this problem could happen to others when trakt changes the pages of the show ^^

**Comment by michaldrabik** [comment]
Sure, I'm not sure what causes this edge case. I think Trakt is sometimes messing around with the ids and that could cause an issue. I personally never had this happened to me and I've been working with the app for quite some time now :)

Feel free to reopen on case of any more problems.
