### ISSUE TITLE
Fixed in portrait mode?

### ISSUE THREAD

**Issue by tibbsbrookside** [michaldrabik/showly-2.0#459]
Not sure if it's just me (couldn't find anyone else reporting this) but, I've installed the app on a couple of Android devices (running different ROMs and both with autorotate enabled) and the app appears to be fixed in portrait mode.

Is this by design or is there any option to enable landscape / auto rotate? Thanks.

**Comment by michaldrabik** [comment]
@tibbsbrookside Yes the app is currently locked to portrait mode only.

**Comment by tibbsbrookside** [comment]
Thanks for the quick response.

Could I request that landscape mode / auto rotate functionality be added if possible.

I'm no developer so can't help with any coding but, I'd be happy to assist with any testing.

**Comment by michaldrabik** [comment]
I've been thinking about it but it's not something I will be focusing on right now. There are lot's of things in my backlog already but eventually when I'm happy with the state of the app I will be adding landscape support (it's not a small task actually.).
