### ISSUE TITLE
Update Project Setup README to include RedditClientId

### ISSUE THREAD

**Issue by mak1nt0sh** [michaldrabik/showly-2.0#468]
I tried building the project in current README and I just noticed that RedditClientId is required [here](https://github.com/michaldrabik/showly-2.0/blob/674580d8109c028e9839a3a1cc066196521bf2f1/data-remote/build.gradle#L29).

**Comment by michaldrabik** [comment]
@mak1nt0sh Yes. I've added it recently and have not updated readme yet.
