### ISSUE TITLE
Ratings for seasons

### ISSUE THREAD

**Issue by MichalisSak** [michaldrabik/showly-2.0#475]
Add the ability to rate and show ratings for seasons.

Rating episode by episode could be boring during watching a series (so maybe some users would prefer just rating the season after completion) and rating whole season would be easier for shows that you've already watched and remember how much you like them (so people could "transfer" some more ratings instead of just rating the whole show, if they moved recently to trakt and showly).

This is implemented on trakt, and it would be useful for shows that you are not sure worth continuing.

**Comment by samyelias** [comment]
I also find rating seasons very useful, even in addition to individual episode ratings; it's on Trakt, so Showly should be able to do it too.

**Comment by michaldrabik** [comment]
Rating seasons will be possible starting with version 3.11
