### ISSUE TITLE
Add links to Metacritic and Rotten Tomatoes

### ISSUE THREAD

**Issue by Victor239** [michaldrabik/showly-2.0#478]
The Link feature should also have these two other highly popular review aggregators (which I personally find less biased than other aggregators also).

**Comment by Victor239** [comment]
This would be defunct by adding #479

**Comment by michaldrabik** [comment]
Will be adding an extended links section soon but you can already use RT and Metascore links starting with latest update (3.1.0) by clicking relevant ratings in details screen.
