### ISSUE TITLE
Support search providers as custom Links

### ISSUE THREAD

**Issue by Victor239** [michaldrabik/showly-2.0#479]
Desktop browsers like Chrome and Firefox allow [easily adding various websites as search providers](https://www.howtogeek.com/114176/HOW-TO-EASILY-CREATE-SEARCH-PLUGINS-ADD-ANY-SEARCH-ENGINE-TO-YOUR-BROWSER/), or you can use search plugin websites like [Mycroft Project](https://mycroftproject.com) to add them in one-click. These are basically just URL strings, like DuckDuckGo's one is `https://duckduckgo.com/?q=%s`and your search phrase gets added at the end to do a search.

It would be very useful if strings such as DuckDuckGo's, YouTube, Twitter, etc could be added as a custom Link which could easily be searched from a TV show or movie webpage. For example if viewing the Nobody movie page, then a custom Link for YouTube could be clicked, which would search "Nobody movie" for you so you can easily see reviews, reaction videos, alternate trailers, etc.

If viewing the Power TV show, then clicking a custom Link for Twitter would search "Power TV show", which would allow the user to see everyone's thoughts about the show, latest news, find the Twitter account for it, etc. I think you get the gist - it makes the Showly really powerful for finding related information about the movie or TV show.

**Comment by michaldrabik** [comment]
Links menu has been updated and more options has been added in v.3.7.0
![image](https://user-images.githubusercontent.com/11537045/141951967-4ecf0896-dc45-4043-b6c6-ed6bef702f1f.png)
