### ISSUE TITLE
Actor image alignment off centered

### ISSUE THREAD

**Issue by crxssed7** [michaldrabik/showly-2.0#481]
The actor image alignment is off centered when the character / actor name is too long, see below screenshot relating to the show "Sonic Underground": 
![image](https://user-images.githubusercontent.com/48864420/116888385-4f590900-ac23-11eb-8d83-7cbc83e891d5.png)

**Comment by michaldrabik** [comment]
@crxssed7 Thanks for spotting. It was a quick fix and will be released next update.
