### ISSUE TITLE
Forced capitalization

### ISSUE THREAD

**Issue by Mannivu** [michaldrabik/showly-2.0#482]
I've recently noticed that the app uses (at least in Italian) a forced capitalization for titles. I'd like the app using the titles as they're written on TVDB and TMDB databases.

**Comment by michaldrabik** [comment]
Titles are actually taken from Trakt.tv. They are usually capitalized - not sure about Italian and other languages but I will check

**Comment by michaldrabik** [comment]
I do actually force capitalization in code anyway. Might be better to turn it of an let the title display as it is in Trakt source

**Comment by Mannivu** [comment]
If that's possibile, that would actually be great, since at the moment it creates weird capitalization in italian titles (since sometimes we have articles bound to the following noun).
