### ISSUE TITLE
Custom list ranking not working

### ISSUE THREAD

**Issue by elvis0288** [michaldrabik/showly-2.0#484]
Hello man, so i went into trakt today and it looks like the ranking i did to my custom list is not reflecting into trakt. so for example i added 2 new shows into my TOP TV SHOWS custom list through the app and then i clicked on rank and moved them to a different position. this is how it looks on the app:
![WhatsApp Image 2021-05-06 at 12 40 47 PM](https://user-images.githubusercontent.com/7027367/117292699-689ec700-ae68-11eb-9b34-1423d5817f0d.jpeg)
![WhatsApp Image 2021-05-06 at 12 40 47 PM (1)](https://user-images.githubusercontent.com/7027367/117292703-69cff400-ae68-11eb-9143-53b2b12dd0e2.jpeg)

the 2 tv shows i added were taken and the tomorrow people they are on position 11 and 28.. now if i go into trakt, it looks like adding them is ok as they were added to the list but they will just show at the end of the list:
![image](https://user-images.githubusercontent.com/7027367/117292830-8bc97680-ae68-11eb-944d-3022dcdeb70b.png)

Thanks!

**Comment by michaldrabik** [comment]
Hi @elvis0288 .

Unfortunately the rank order is not synced between Showly and Trakt lists. They are preserved separately.
This is because in Trakt a user can also have episodes and seasons as element of their lists. As Showly does not support single episodes and seasons in any lists in general it would be impossible maintain a proper order.

**Comment by elvis0288** [comment]
oh that really sucks.. so it is the same issue the other way around? i just try to modify the order on trakt and it was not sync into showly

**Comment by michaldrabik** [comment]
Yes, sorry. Order is ignored during sync. As I said. I would have destroyed users order if they have any episodes or seasons in their list.

**Comment by elvis0288** [comment]
yeah i understand so is showly somehow been store on the cloud? let's say i start doing my ranking on the app and i switch phone or my phone breaks. when i install showly again will that order be there or the first time it will sync with trakt?

**Comment by elvis0288** [comment]
i found a workaround which is keeping my ordering through trakt and then when i want to see the order correctly on showly i would delete the list without removing it from trakt. then when i sync again it will import it back with the right ordering

**Comment by michaldrabik** [comment]
@elvis0288 Yes, just wanted to write this. When the list is imported from Trakt for the first time the order will match Trakt's.
