### ISSUE TITLE
Don't show unaired episodes in progress bar

### ISSUE THREAD

**Issue by LutzRyan** [michaldrabik/showly-2.0#486]
I've recently found your project and I like it better than any other trakt clients I've come across. I found one thing that I don't like. In the progress activity, it tells you how many you watched and how many are left to watch. For shows that are ongoing, episodes that have not aired yet are included in the "left to watch" count. Instead, it would be more useful if it showed "episodes watched/episodes aired (% watched)" with maybe a status on on how many have not aired yet.

I started playing with the code and found that ProgressMainItemView.kt would need to change to this in bindProgress: 
`val percent = ((item.watchedEpisodesCount.toFloat() / item.show.airedEpisodes.toFloat()) * 100).roundToInt()`
`val leftToAir = item.episodesCount - item.show.airedEpisodes`
`progressItemProgress.max = item.show.airedEpisodes`
`progressItemProgress.progress = item.watchedEpisodesCount`
`progressItemProgressText.text = String.format(ENGLISH, "%d/%d (%d%%) (%d not aired)", item.watchedEpisodesCount, item.show.airedEpisodes, percent, leftToAir)`

I haven't done full testing on that, but it might be a start for you if you like this.

**Comment by michaldrabik** [comment]
I understand your point but I always felt like it makes much more sense that progress includes total number of episodes. Including the one that have not aired yet. If feels weird showing progress as 100% when there are still 5 episodes to come next week for example.

**Comment by michaldrabik** [comment]
Starting with latest version total number of episodes will only include aired episodes. Seems like more users prefer it this way so I've decided to change it.
