### ISSUE TITLE
Calendar history

### ISSUE THREAD

**Issue by beam** [michaldrabik/showly-2.0#488]
it would be good if you could browse the history of the calendar.
Something like in https://play.google.com/store/apps/details?id=com.jonathanantoine.TVST

**Comment by fabianski7** [comment]
https://github.com/michaldrabik/showly-2.0/issues/457

**Comment by michaldrabik** [comment]
Starting with latest version calendar allows to see recently aired episodes dating 3 months back.

**Comment by beam** [comment]
Cool, thanks.
