### ISSUE TITLE
Difference between Portuguese from Portugal and Brazil

### ISSUE THREAD

**Issue by fabianski7** [michaldrabik/showly-2.0#496]
In the settings in the app, [it is possible to select the Brazilian Portuguese](https://user-images.githubusercontent.com/47755037/121078626-b8a2dd80-c7c8-11eb-8f7a-697a3b43e79c.jpg) language for the description language and titles, but what is being displayed is the Portugal version.

See this example for the movie Ferris Bueller's Day Off:
The app show [O Rei dos Gazeteiros](https://user-images.githubusercontent.com/47755037/121078786-e6882200-c7c8-11eb-8f98-1fd17d5d6d42.jpg), but the Brazilian version has the title [Curtindo a Vida Adoidado](https://user-images.githubusercontent.com/47755037/121078694-cb1d1700-c7c8-11eb-9b9c-4020e59a8f21.jpg)
Source: https://pt.wikipedia.org/wiki/Curtindo_a_vida_adoidado

**Comment by michaldrabik** [comment]
@fabianski7 Hi!.

Translations come from Trakt API and there is not much I can do. 
Trakt only has "PT" language, there is no specific PT-BR flavour.

Below you can find full response with translations for that movie:
https://gist.githubusercontent.com/michaldrabik/937dc48b84a5b2c88c01981fea195f50/raw/ca0ec7ebccd7dd230c946b6801527a45a27ab7ee/gistfile1.txt

**Comment by fabianski7** [comment]
I understand. I thought they came from IMDB or TMDB
