### ISSUE TITLE
Poster sometimes doesn't show

### ISSUE THREAD

**Issue by crxssed7** [michaldrabik/showly-2.0#501]
Not sure if this is a bug or if it was somewhat intended, but some lesser known TV shows don't show the poster. However I have realized that sometimes when first loading the app the poster does show, but when changing pages it disappears again. Take PBS Eons for example:-

<h3>When loading the app:</h3>

![image](https://user-images.githubusercontent.com/48864420/122116734-dce06900-ce1d-11eb-8468-786423c3c640.png)

<h3>After changing the page and then going back to progress tab</h3>

![image](https://user-images.githubusercontent.com/48864420/122116821-fda8be80-ce1d-11eb-9657-fd1eac58aa09.png)

I have realized that TV shows that don't have a TMDB or IMDB record are the ones that do this.

Let me know if I need to explain further or if this was intended.

**Comment by michaldrabik** [comment]
Hi @crxssed7 
This might happen for some lesser known shows that are not on TMDB. Actually all images are taken from TMDB. The app will sometimes try other source as a backup though. I can see that image did actually show for a second in your case so I will take a look at this later. Might be some caching bug there.

Thanks

**Comment by michaldrabik** [comment]
The main issue here is that Trakt does not have a reference to TMDB ID for this show. I've raised the issue with Trakt support and hopefully it will be resolved soon, thanks!
