### ISSUE TITLE
Identify the director of the film 

### ISSUE THREAD

**Issue by gitvnt** [michaldrabik/showly-2.0#513]
In addition to the list of actors, would it be possible to have the film's director in the film's file?

**Comment by olavinto** [comment]
Yes, I'd like to up this to adding a separate section for crew. Not the whole crew but director(s), producers, writers and such would be nice. Director is a must have and I hadn't actually noticed before that it wasnvt already available.

**Comment by michaldrabik** [comment]
One of the upcoming updates will be only devoted to updating People section for shows and movies. Planning to add info about directing/writing/music but also new sections with details for the people like other shows/movies they appear on sorted by date. etc.

Basically new profile details screen.

**Comment by michaldrabik** [comment]
Added in v 3.10.0
