### ISSUE TITLE
Automatically mark movie/episode as watched on Trakt when rating

### ISSUE THREAD

**Issue by rfgamaral** [michaldrabik/showly-2.0#519]
It would be nice to have a movie/episode being marked as "watched" on Trakt automatically after rating said movie/episode in the app. I mean, I usually rate something after I watch it, so it kinda makes sense to automatically add it as "watched" in this particular case.

However, I understand this might not be the case for everyone, so maybe this should be behind a setting of sorts? Just a suggestion.

**Comment by michaldrabik** [comment]
@rfgamaral An inverted version of this feature is currently available for premium users (quick rate - rate episodes/movies when you mark them as watched automatically) so I'm not planning on touching it right now.

Hope it's OK with you :)

**Comment by rfgamaral** [comment]
I understand, but I wish the reserve was also possible.
