### ISSUE TITLE
[Request] Add a Calendar section in the watchlist tab to see what new episodes are coming

### ISSUE THREAD

**Issue by oathzed** [michaldrabik/Showly-2.0#52]
Check out the app "Hobi" to see a reference :). Thanks! Awesome app!

**Comment by michaldrabik** [comment]
Hi. Yes I've seen it in Hobi but I really did not want to copy it (and was not so fond of this).
The "calendar" is a part of Watchlist in showly. Incoming shows are listend under "Coming Soon" and sorted by date along with time left information

![obraz](https://user-images.githubusercontent.com/11537045/84419396-d6228300-ac18-11ea-9ff5-c0c9aac97645.png)

**Comment by michaldrabik** [comment]
Now tracked in #56
