### ISSUE TITLE
Cannot load images

### ISSUE THREAD

**Issue by Ojd2000** [michaldrabik/showly-2.0#523]
I've recently switched to LineageOS for microG 18.1 from OxygenOS.
Before the app worked fine, but now it does not load any images at all. The rest of functionalities is fine.

**Comment by michaldrabik** [comment]
@Ojd2000 I do not test any custom OSes to be honest but perhaps this was just temporary? Do you still have an issue even after reinstalling Showly app?

Regards

**Comment by Ojd2000** [comment]
@michaldrabik No, I still have this issue, but I don't think this is due to the custom ROM.
I usually use OAndBackupX to backup my apps data, and I did the same with Showly. When I restore it, it gets in fact restored, but for some reason the images are not shown. Not only the images of the restored items, but also all the other images the app may download.

**Comment by michaldrabik** [comment]
Hmm. Does Clear Images Cache option from Settings help?

**Comment by Ojd2000** [comment]
Nope, I tried more than once.

**Comment by michaldrabik** [comment]
@Ojd2000 It might be something with that backup but at this point my only advice is to perform clean install of the app which should help.

1. Export your data to Trakt.tv to make sure you don't lose it.
2. Uninstall the app and install again.
3. Import your collection from Trakt.

**Comment by Ojd2000** [comment]
Yeah, I forgot to mention that I do not use Trakt.tv, that's why I do backups this way.
Thanks anyway.

**Comment by michaldrabik** [comment]
@Ojd2000 Sure but just for the sake of this issue you can quickly create some fake Trakt.tv account temporarly and use it to perform clean install.

**Comment by Ojd2000** [comment]
@michaldrabik I can confirm that with Trakt.tv sync there is no problem.
