### ISSUE TITLE
Gridview option

### ISSUE THREAD

**Issue by vyktorjonas** [michaldrabik/Showly-2.0#53]
Have you considered that? As an option to the current list view? I think it'd look better and fit more shows on the screen

**Comment by michaldrabik** [comment]
Which part of the app do you mean?

**Comment by vyktorjonas** [comment]
Watchlist, with posters on top and the name/number of ep right on the botton.
Also, if I may, I don;t think there's any reason for the "2.0" on the app name on the drawer

**Comment by michaldrabik** [comment]
There is too much information that needs to be displayed in a watchlsit item for it to be a Grid item. Also smaller screens might not handle it too well.

Also 2.0 will have to stay for now as previous version of Showly is still availble in PlayStore and it would duplicate.
