### ISSUE TITLE
Hide shows and movies from Discover

### ISSUE THREAD

**Issue by LavelleRegister** [michaldrabik/showly-2.0#534]
I'm a user, not a coder! I created this account to comment here. I switched to Showly from TV Favs.

One feature I would like- I want to be able to hide movies and shows from the Discover lists. Something like the Paw Patrol movie is not going to be on my list of shows, so I would love to hide it forever.

**Comment by michaldrabik** [comment]
@LavelleRegister Hello, you can do this already with Archive. To move something into Archive first you need to move it into Watchlist or My Movies/My Shows and then Archive button will appear.

Archived items are excluded from showing up.

**Comment by gitvnt** [comment]
Unless I am mistaken, the Archive option is not available for films. It is only available for series. Would it be possible to add it?

**Comment by michaldrabik** [comment]
That is correct. With that in mind I will be considering refactoring Archive into "Hidden" section for both Shows and Movies. This could also be synced with Trakt hidden items in that case.

**Comment by gitvnt** [comment]
Great ! In this case it answers the problem I posed in ticket #512. I will therefore close it.

**Comment by michaldrabik** [comment]
Will be tracked in #538
