### ISSUE TITLE
Builded from source: No images seem loading

### ISSUE THREAD

**Issue by esQmo** [michaldrabik/showly-2.0#539]
I just builded from sourece. I have all keys, set up however images are not loading and log shows Glide failing to open images urls. Log also shows some error about api key being invalid, but my keys works . It seems like Showly is trying to fecth some images from  https://artworks.thetvdb.com

**Comment by michaldrabik** [comment]
Do you mean all of the images or just some?

**Comment by esQmo** [comment]
All the images. There is some api key issues which makes Glide  fails to retrieve images from urls. But can't tell which key the log is referring? I can fetch data though

**Comment by michaldrabik** [comment]
Most likely something is wrong with yout TMDB key (TMDB is used as a main images source). Make sure you got that set up correctly and you are using the v4 TMDB api key (the long one)

**Comment by esQmo** [comment]
Ah! Was using V3 api key. I recall reading in code somewhere you were using v3 though. I will try v4 then
