### ISSUE TITLE
Fix "fr"/"fr-CA" french titles or separate the settings for UI and titles language

### ISSUE THREAD

**Issue by nbz6** [michaldrabik/showly-2.0#546]
Hi,

The actual setting for language change both UI language and titles language.

In France if we select the "French" settings here, a lot of titles are translated in what I think is "French Canadian" (=fr-CA) and not the titles that we usually use in France (=fr).

Would it be possible to do any of the following : 
1. Fix the "fr" / "fr-CA" issue by using the combo "Language"+"Region" settings to adjust the title, so "French"+"Canada" = "fr-CA" and "French"+"France" = "fr".
2. Fix the "fr" / "fr-CA" issue by separating "French" (=fr) and "French Canada" (=fr-CA) in the "Language" settings for the title.
2. Separate the settings for UI language and titles language, like that anyone can choose whatever is good for them, this way at least we could have the UI in french and titles in English which is closer to the titles we usually know.

**Example :** 
https://www.themoviedb.org/tv/80752-see?language=fr
https://www.themoviedb.org/tv/80752-see?language=fr-CA

In France we should have "See" and in the Canada "Jour Noir".
With the actual settings we all have "Jour Noir".

Thank you, really great app !

**Comment by nbz6** [comment]
I have opened a similar issue in https://support.trakt.tv/ to be able to split "fr-FR" and "fr-CA".
I will let you know if I have a return.

**Comment by michaldrabik** [comment]
@nbz6 Sure

**Comment by michaldrabik** [comment]
Closing this for now as its not related to the app. But please feel free to reopen it if anything comes up.
