### ISSUE TITLE
"New" episode for an old watched TV show lack of visibility 

### ISSUE THREAD

**Issue by nbz6** [michaldrabik/showly-2.0#547]
Hi,

"New" episode for an old watched TV show or previously 100% watched TV show can have a lack of visibility in my opinion.
I have a long list of TV show to follow, so I like the sort by "Recently Watched" to keep up on my list my current watchs.
But if a new episode of a old TV show is aired, in that case it will be down in the botton of the list.

![Screenshot_20211108-132127p](https://user-images.githubusercontent.com/4399512/140833913-f8dc7f72-d2ed-4ef0-8121-76c6d24dae1f.jpg)

Would there be a way to make them more visible ?
Episode with the tag "new" could be temporary on top of the list ? (but the tag does not last long, 1 day ?)

Or a new "Suggestions" list section on top of the "sort by" list that offers a top to watch with a mix between recently watched episode and a new episode from a previously 100% watched TV show (because that show have a strong chance that the user want to watch it). That way people that want any other "sort by" could have that section to follow their current watch on the top too.

Best regards

**Comment by olavinto** [comment]
I agree. Could also use a corner style indicator overlayed on the poster like is a common practice to mark watched/unwatched status for Kodi skins etc. for example. Or perhaps a light background color for tve whole row in addition to the current icon/text to highlight it a bit more.

**Comment by nbz6** [comment]
The light background color seems to be a good idea.
But mainly, "new" episode should stay on top of the list for at least 3-4 days :
-> 1 day is very short for people who aren't watching shows live on TV (the time to see it in VOD or wait for a subtitle to be ready) or the first day of the release on streaming services.
-> People with long list of TV shows to watch, "new" episodes can sometime be on the bottom of our list for an old TV show and we can't see them.

**Comment by olavinto** [comment]
> 
> 
> The light background color seems to be a good idea. But mainly, "new" episode should stay on top of the list and for at least 3-4 days : -> 1 day is very short for people who aren't watching shows live on TV (the time to see it in VOD or wait for a subtitle to be ready) or the first day of the release on streaming services. -> People with long list of TV shows to watch, "new" episodes can sometime be on the bottom of our list for an old TV show and we can't see them.

Add an option to customize the time.

**Comment by michaldrabik** [comment]
What I'm thinking right now - that every user should be OK with - is to bring all the NEW episodes to some kind of top section located below pinned items (those should have priority I think).

This section should be dismissable by user's manual action (click to acknowledge). After manual acknowledging shows from "New" subsection would return to their normal position according to current sorting. 

If the section is not dismissed by users shows should drop out of it automatically after some time. NEW badge is currently set to 24 hours so that could be increased to 3-4 days I believe.

**Comment by Alexc26** [comment]
I've only just started using showly, swapped over from TV Time and already this is one of the features I miss a bit from it. Having the new episodes at the top for at least a couple of days would be alright.

**Comment by Alexc26** [comment]
Any possible chance of this being implemented?

**Comment by blackholeearth** [comment]
This feature is available in app now.

Can close this..
