### ISSUE TITLE
Watching vs Returning

### ISSUE THREAD

**Issue by kosorin** [michaldrabik/showly-2.0#551]
Why are some shows in Watching section and others in Returning & upcoming.
For example, The Walking Dead is in Watching section and Fear the Walking Dead is in Returning section, but both shows have not finished yet.

**Comment by michaldrabik** [comment]
Hello. It depends on how much of them you have watched already.

Watching -> You still have some episodes left to see
Returning Upcoming -> Everything is watched. Waiting for new episodes/seasons.

Regards,
Mike

**Comment by kosorin** [comment]
So, I suppose Showly just has bad data from Trakt, TMDB or other sources.

I watched all episodes but one. Missing episodes airs next year.

The Walking Dead - Watching section
![image](https://user-images.githubusercontent.com/13920314/146648593-54ed7db5-84c4-4bff-bf0a-b30b6cf2e865.png)

Fear the Walking Dead - Returning & Upcoming section
![image](https://user-images.githubusercontent.com/13920314/146648601-a761699d-5e4d-472c-a0e1-c4e14f1c2aa2.png)

**Comment by michaldrabik** [comment]
I think it's about the season 7 status which is weird. It is marked as watched but it's 8/9.

Are you able to uncheck season 7 and check it again?

**Comment by kosorin** [comment]
I was able to uncheck and check again watched episodes. That fixes the problem. I can't check again season 7. 

However, I have no idea why it was checked. I never mark the whole season as watched.

**Comment by michaldrabik** [comment]
I have a theory but will need to investigate. Most probably you had all 8 episodes watched and then new one appeared and this case was not handled properly (season remained completed)

**Comment by michaldrabik** [comment]
Located and fixed the bug mentioned above. Thanks for opening this issue as I was not aware of this behaviour
