### ISSUE TITLE
Feature Request: Simkl

### ISSUE THREAD

**Issue by saru-man** [michaldrabik/showly-2.0#562]
I would love to see support for Simkl added to Showly as a second tracking backend - ideally Showly would be able to send updates to both trackers in parallel.

**Comment by michaldrabik** [comment]
This is most probably never going to happen. Sorry. Having to maintain two separate backend solutions and keep everything in sync would be a huge undertaking. Not to mention that Trakt API does not provide Simkl ids for any of their data so It might be an impossible task even.

**Comment by saru-man** [comment]
Thanks for the quick response - I'll close the FR. :)

**Comment by masyk** [comment]
You don't need to use Simkl IDs. Simkl accepts TVDB, IMDB, and TMDB ids to sync. You also don't need to send episode IDs as Simkl works with the season and episode numbers instead of ids. https://api.simkl.com

**Comment by 002gRTEah3mRYH** [comment]
There is wako, both trakt and simkl client, but not foss

**Comment by mystrdat** [comment]
I think Simkl is slowly but surely stealing users from Trakt, it's recommended more often it the various discussions you find on the web and has almost surpassed Trakt on the "alternative to" comparison sites.

My generalized impression is that Trakt has been sleeping for the last decade, mostly investing in their VIP features, and it probably hasn't been as much of an issue since most people use it for the API sync as a generic tracker database. In that area, Simkl seems to do just about everything better. And then it's also incomparably friendlier to new users due to the flawless imports from IMDB etc.

So I hope you reconsider at some point since this is IMO a matter of time and request for Simkl support will be growing.

**Comment by 002gRTEah3mRYH** [comment]
> I think Simkl is slowly but surely stealing users from Trakt, it's recommended more often it the various discussions you find on the web and has almost surpassed Trakt on the "alternative to" comparison sites.
> 
> My generalized impression is that Trakt has been sleeping for the last decade, mostly investing in their VIP features, and it probably hasn't been as much of an issue since most people use it for the API sync as a generic tracker database. Even in that area, Simkl seems to do just about everything better, but it also feels like an actual platform of its own. It's also incomparably friendlier to new users due to the flawless imports from IMDB, it's own easy to use Discord bot, better auto-trackers... List goes on.
> 
> So I hope you reconsider at some point since this is IMO a matter of time and request for Simkl support will be growing. I'd surely love to have it myself. ❤️

I use Simkl as a backup of Trakt, cause simkl has an import feature.

I'd like to dev a personnal app based on seriesguide ie, and implement both. As said, Wako does that but not fodd and had ads..

**Comment by rollingmoai** [comment]
> I think Simkl is slowly but surely stealing users from Trakt, it's recommended more often it the various discussions you find on the web and has almost surpassed Trakt on the "alternative to" comparison sites.
> 
> My generalized impression is that Trakt has been sleeping for the last decade, mostly investing in their VIP features, and it probably hasn't been as much of an issue since most people use it for the API sync as a generic tracker database. Even in that area, Simkl seems to do just about everything better, but it also feels like an actual platform of its own. It's also incomparably friendlier to new users due to the flawless imports from IMDB, it's own easy to use Discord bot, better auto-trackers... List goes on.
> 
> So I hope you reconsider at some point since this is IMO a matter of time and request for Simkl support will be growing. I'd surely love to have it myself. ❤️

Unfortunately, Simkl doesn't have much integration with apps. They don't have a Linux or Mac Scrobbler, in Windows they don't support MPV, and Stremio doesn't support Simkl. Unfortunately, I use all of those, so I can't switch.
