### ISSUE TITLE
Add a "# (of eps) left" counter below eps watched/total eps in Progress tab

### ISSUE THREAD

**Issue by johngarciava** [michaldrabik/showly-2.0#564]
Hello, this is a suggestion. I find myself doing the mental calculation of subtracting 'total eps - eps watched' a lot, I think it would be very nice, a quality of life change, to show the result of that subtraction right below it with the same styling:

![image](https://user-images.githubusercontent.com/29204882/148344453-dd833b3d-8fb5-495b-a980-530147a3a1e0.png)

An example of what I'm referring to:

![image](https://user-images.githubusercontent.com/29204882/148344597-5978978b-7214-4b9d-a374-6abcdba7163c.png)

That being said, If you think showing the eps left + the percentage is redundant, then in that case I would prefer to drop the percentage and keep the eps left counter. Obviously I can't speak for other users, but like I said I find myself trying to make that mental calculation a lot subconsciously, and a lot of times it's tedious because it's not always simple numbers. 

I think the replacement, if you find it necessary to choose one over the other, makes more sense to go with the '# left' because I, and I imagine most people, don't ever find themselves saying "oh, I'm 73% of the way there", or "I got 6% left to go". In casual convo, whether text or spoken, I usually give people hard numbers, "I have x episodes left to watch". Percentages can be misleading and can give an impression of there being a lot of binge-watching to do when there really isn't, for example 50% left to go on a show with 50/100 eps is also 50% left on a show being 5/10 eps.

Also, if you were to sort your progress section by 'Episodes Left', this possible change would also make it extremely easier for the user to see that the sort was done correctly, as the user won't need to make any mental calculations to be sure.

I know the pin logo is essentially taking up the space of where the counter could be placed, so if you do like the idea and end up implementing it, I imagine rearranging the layout there and see where things would end up being is gonna be interesting.

**Comment by michaldrabik** [comment]
Hi. Currently I'm simply considering switching percentages to number of episodes left:

**69/170 (41%)** would become **69/170 (101 eps.)**

What do you guys think about this. Is the percentage even necessary there from user point of view?

**Comment by johngarciava** [comment]
Hey,

In my opinion replacing the percentage to number of eps left is the best move. Percentage + progress bar is redundant.

Visually and semantically, the alternative you pose, **69/170 (101 left)**, is better than **69/170 (101 eps.)**. "X left" is more apprioriately meaningful and also more generally applicable ("1 eps." would look weird).

**Comment by Tomekske** [comment]
I'd use both percentage and "episodes left". When watching a tv show with lots of seasons it's nice to know the percent of completed episodes.  But just like @johngarciava, I tend to mentally calculate the "episodes left" within the "TV show detail page" as well. I added an image with a suggestion below.

![image](https://user-images.githubusercontent.com/22329280/152041171-87671a33-0537-4092-b81a-db779a7d89e2.png)

**Comment by Fooftilly** [comment]
> I'd use both percentage and "episodes left". When watching a tv show with lots of seasons it's nice to know the percent of completed episodes. But just like @johngarciava, I tend to mentally calculate the "episodes left" within the "TV show detail page" as well. I added an image with a suggestion below.
> 
> ![image](https://user-images.githubusercontent.com/22329280/152041171-87671a33-0537-4092-b81a-db779a7d89e2.png)

In my opinion, both options shouldn't be visible at the same time. Instead of showing both, it would be nice if we can click on the time left and it would change to episodes left, and if you click it again it would display the time remaining. Maybe add an option in setting which of the two should be visible by default. Adding too much information on the screen could make them visually distracting to those users who don't find that information useful.

**Comment by Tomekske** [comment]
> > I'd use both percentage and "episodes left". When watching a tv show with lots of seasons it's nice to know the percent of completed episodes. But just like @johngarciava, I tend to mentally calculate the "episodes left" within the "TV show detail page" as well. I added an image with a suggestion below.
> > ![image](https://user-images.githubusercontent.com/22329280/152041171-87671a33-0537-4092-b81a-db779a7d89e2.png)
> 
> In my opinion, both options shouldn't be visible at the same time. Instead of showing both, it would be nice if we can click on the time left and it would change to episodes left, and if you click it again it would display the time remaining. Maybe add an option in setting which of the two should be visible by default. Adding too much information on the screen could make them visually distracting to those users who don't find that information useful.

I totally get what you mean, I think a tooltip could be a possible solution to this issue

**Comment by michaldrabik** [comment]
Im hesitant about adding this into details and making it clickable AND adding special tutorial tip just for that. I think it's really not that necessary at all as here you can actually see all the seasons with count so it's not that bad. I think for now I'll start with changing % to eps. left in Progress items views.

**Comment by Francy115** [comment]
I'd keep both percentage and episodes left, there are many shows or animes with a lot of episodes:
![Screenshot_20220204-095547_Showly](https://user-images.githubusercontent.com/98353972/152500653-e64a45cf-d369-4a1d-9447-819483744f2b.jpg)
![Screenshot_20220204-095925_Showly](https://user-images.githubusercontent.com/98353972/152500840-92ebf464-16e0-4ae6-b23e-1214c0b8c45b.jpg)
And "316"  or "744" episodes left would sound off
In my opinion, having the possibility to toggle between them would be a good idea

**Comment by michaldrabik** [comment]
@Francy115 Having it as "316 left" would still give you better information though would it not? 
And percentage can be visually seen on the red progress bar.

**Comment by Francy115** [comment]
> @Francy115 Having it as "316 left" would still give you better information though would it not? And percentage can be visually seen on the red progress bar.

I think the percentage would suit better in this case, in shows with so many episodes. For instance, it's unlikely that I'll ever see all the episodes of Family Guy or The Big Bang Theory, just a few episodes occasionally. So knowing you've seen "37%" of that show would look nicer than "700 episodes left", at least in my opinion.

**Comment by michaldrabik** [comment]
@Francy115 I guess I can't please everybody :) I've tested a solution with this value changing on a click but I don't like it as the episodes label is kind o fin the middle of the whole list item and very often I found myself wanted to open show's details and tapped the value which casued value swap insted of opening details. Pretty annoying.

**Comment by johngarciava** [comment]
I honestly don't see how showing the percentage is better than showing episodes left just because it might feel better with shows for a large number of episodes.

As long as you know the total number of episodes which is always shown, being shown the percentage still "feels bad" because you know you still have a large number of episodes left to go.

The benefit of showing the percentage just for shows with large number of episodes, if any benefit at all, is heavily outweighed by the immense benefit of being shown a hard number of episodes left that is actually useful information for any type of show.

**Comment by michaldrabik** [comment]
Will be waiting for release.
