### ISSUE TITLE
TV Show collection missing shows

### ISSUE THREAD

**Issue by andyfore** [michaldrabik/showly-2.0#565]
Not all of the shows in my Trakt collection are visible.  It seems that a show doesn't appear in the collection until an episode has actually been watched.  Is the intentional?

**Comment by michaldrabik** [comment]
Yes. Becasue Trakt.tv website does not really allow you to have a 0 episodes progress only when there is at least one the show will appear in your `https://trakt.tv/users/USERNAME/progress` section.

If a show is visible in this section it will also be imported into the app.
