### ISSUE TITLE
Improvement - Display total amount of series in a list 

### ISSUE THREAD

**Issue by Tomekske** [michaldrabik/showly-2.0#566]
Hey, I was wondering whether it's possible to add the total amount of series within a list. I know it's possible to sort by 'rank' but it's a tedious way to determine the total amount of series in your list.

![image](https://user-images.githubusercontent.com/22329280/149304516-623c31c4-3f06-4eb7-8c80-383af28ab0ad.png)

**Comment by michaldrabik** [comment]
Yeah I need to code this finally. Had this thought long time ago.

**Comment by michaldrabik** [comment]
Pending for release.
