### ISSUE TITLE
Trakt.tv not syncing

### ISSUE THREAD

**Issue by sjohal91** [michaldrabik/showly-2.0#567]
Having issues syncing with trakt.tv since Friday. Anyone else having issues? When trying to sync it says sync failed.

**Comment by sjohal91** [comment]
I think I've found out it has something to do with Adguard

**Comment by michaldrabik** [comment]
@sjohal91 Can you give more details. I'm also using AdGuard DNS but everything seems to be working just fine.

**Comment by sjohal91** [comment]
I was using the Adguard app and turning protection off for the app fixed
the issue.

Sean Johal
