### ISSUE TITLE
Not available to download on Brazil

### ISSUE THREAD

**Issue by Khrona98** [michaldrabik/showly-2.0#568]
I recently stumbled on this app and would really like to download it, but it is not available to download here on Brazil, I tried to download it with 2 different devices just to be sure.

Would it be possible to allow my country to download it from Google Play?

**Comment by michaldrabik** [comment]
@Khrona98 I'll see about that. Just in case you can always get the latest release APK here:
https://github.com/michaldrabik/showly-2.0/releases
