### ISSUE TITLE
[Feature Request] Cross-sync with TMDB account

### ISSUE THREAD

**Issue by Jacekun** [michaldrabik/showly-2.0#580]
It would be great to have the ability to sync with themoviedb account, when an entry is either added to "My Movies" or its rated.

[Related API link](https://developers.themoviedb.org/3/movies/rate-movie).

**Comment by michaldrabik** [comment]
I do not plan doing this unfortunately at this time. I want to keep Trakt as a single source of data. Syncing multiple sources creates a lot of problems and Trakt uses TMDb to get data internally anyway.

**Comment by Jacekun** [comment]
I mostly meant syncing with watchlist and not as a data source, but understandable. I hope you change your mind in the future.
