### ISSUE TITLE
 instant sync failed. When check mark an episode

### ISSUE THREAD

**Issue by blackholeearth** [michaldrabik/showly-2.0#584]
Since couple of weeks , showly says instant sync failed. All the time. Something is broken with the instant sync.

Even after i log out , log in (trakt auth in settings) when i checkmark an episode ,  notification  says 
İnstant sync failed

**Edit:**  my id

![my id in app](https://user-images.githubusercontent.com/7512105/163955505-c1fdc26d-290e-42ed-baf5-60032a7a6a8f.png)

**Comment by michaldrabik** [comment]
Please send me you app's id so I can check internal logs for any issues. It's located at the bottom of the Settings. Thanks

**Comment by blackholeearth** [comment]
Today. It worked without any error.

Also looked at traktv wesite  ,
 i have changed progress of the tv serie  in the app .
Its shows the same ep count there there.

Everything works. Maybe it was temporary  problem at the traktv site .

**Comment by michaldrabik** [comment]
I could not find anything special in the logs so yeah. Sever issues most likely. It happened a lot lately. Hopefully it's been sorted out.
