### ISSUE TITLE
Long titles in the Widget are not truncated well

### ISSUE THREAD

**Issue by iam0day** [michaldrabik/showly-2.0#586]
![Screenshot_2022-05-05-18-41-09-93_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/17969978/166972300-3819d372-f3cc-4f7e-acea-5abb90e1a1e0.jpg)

The solution might be to put the "Transmitted" under the title

**Comment by michaldrabik** [comment]
Title will not overlap anymore. Waiting for release...

**Comment by iam0day** [comment]
Thank you very much, glad you bought the Premium!
