### ISSUE TITLE
Movies not showing in the movie progress tab

### ISSUE THREAD

**Issue by AnubhavX** [michaldrabik/showly-2.0#588]
I have added many movies but it doesn't show up in the progress tab. It works fine for shows but not for movies
![Screenshot_2022-05-14-13-38-15-139_com michaldrabik showly2](https://user-images.githubusercontent.com/62814612/168417068-d90005b2-3d5e-4192-9162-7320559a4594.jpg)
![Screenshot_2022-05-14-13-38-10-732_com michaldrabik showly2](https://user-images.githubusercontent.com/62814612/168417072-2f769574-6a98-4ee4-bd20-35b4f113044a.jpg)

**Comment by michaldrabik** [comment]
Movies are different in nature so Progress is only relevant for Watchlist movies. The one you added to "My Movies" (so the ones you have seen) will not appear there.

**Comment by AnubhavX** [comment]
I added the movies to my watchlist but they never show up... I haven't seen them yet but they don't show up......what I mean to say is after I add them it should show that I have it pending and I have to watch it after I watch it ill log it in the app then it will get removed from the progress tab..but they don't show there in the first  place

**Comment by AnubhavX** [comment]
I've added these to movies but they don't show up in ky movies tab
![Screenshot_2022-05-21-18-13-55-803_com michaldrabik showly2](https://user-images.githubusercontent.com/62814612/169652049-c75c3df7-c80f-42fb-8e22-2e5907acdcdf.jpg)
![Screenshot_2022-05-21-18-13-47-042_com michaldrabik showly2](https://user-images.githubusercontent.com/62814612/169652053-3bd31962-78f5-4a9b-8a12-e64dc708c915.jpg)
![Screenshot_2022-05-21-18-12-45-336_com michaldrabik showly2](https://user-images.githubusercontent.com/62814612/169652058-3615b0be-d6e1-45a1-b0cc-14b8ff3b8d81.jpg)

**Comment by michaldrabik** [comment]
Ok so just as I have written before and I can now see in you screenshots. You have added these shows into "My Movies" (Added to My Movies).

This means you have already seen them and they will not be displayed in movies progress section.
Try adding a Movie into watchlist with a Watchlist button and you will see it appears in Progress
