### ISSUE TITLE
[Suggestion] Support hiding seasons & episodes

### ISSUE THREAD

**Issue by Abdelrhmanwalid** [michaldrabik/showly-2.0#589]
On Trakt, it's possible to hide individual  episodes or seasons from the next to watch & progress sections, but that doesn't seem to be supported on Showly.
My hidden seasons & episodes are still visible in progress list.
This is useful when watching starting to watch a long running show from the middle with no interest in watching early episodes/seasons.

**Comment by michaldrabik** [comment]
@Abdelrhmanwalid At the moment the app provides a progressive way of following episodes. That means that if you mark an episode in the middle of the season without marking the previous ones a progress will pick up from that marked episode and not the beginning.

Still skipping episodes could be a nice to add later.
