### ISSUE TITLE
Add 'Scoreboard' with ratings

### ISSUE THREAD

**Issue by Donkey-Doug** [michaldrabik/Showly-2.0#62]
Hi,

I have a suggestion for the app. I made a picture to visualize my suggestion:

![Showly concept](https://user-images.githubusercontent.com/50382414/89345886-7be9ef80-d6a8-11ea-95df-6071c980be53.jpg)

It would be really nice to be able to see ratings from several well known websites at a glance.

**Comment by michaldrabik** [comment]
Unfortunately Trakt API does not provide ratings from different sites at this moment (unless I'm wrong but can't find it anywhere in the docs)
