### ISSUE TITLE
Movie network filter

### ISSUE THREAD

**Issue by alexandermeek** [michaldrabik/showly-2.0#626]
The filtering for movies in the discover tab, doesn't  allow filtering by network I.e. only show movies available on Netflix etc.

**Comment by michaldrabik** [comment]
@alexandermeek It's not possible for movies unfortunately.

**Comment by tbleiker** [comment]
Why is it not possible? Was it not possible at that time (mid 2022) or is it still not possible? The info is shown when selecting a movie.

**Comment by michaldrabik** [comment]
@tbleiker Still. It is possible in the details because I can request streamings data and cache it. This is not possible for a lists of movies because you would need to request streaming data for each single item one by one, which is out of question.

**Comment by tbleiker** [comment]
Ah, I see... what a pity!

And out of curiosity, why is it possible for shows?
