### ISSUE TITLE
Sequels and prequels 

### ISSUE THREAD

**Issue by andsofine** [michaldrabik/showly-2.0#627]
add "Sequels and prequels:" over "You may also like:"

It would also be great if it were possible to immediately add the entire series of the film

for example, Star Wars has a lot of films, and adding each one individually is very inconvenient

**Comment by crxssed7** [comment]
I know that TMDb has support for movie collections, so maybe something that implements that?

**Comment by blackholeearth** [comment]
This is implemented, can close now. 

![Zombo-stsrwars-collection](https://github.com/michaldrabik/showly-2.0/assets/7512105/6ae6d025-fc89-48d3-bc00-8af19f20e805)
