### ISSUE TITLE
[Feature request] Differentiate between add to history and add to collection for movies and and series

### ISSUE THREAD

**Issue by tobias-who** [michaldrabik/showly-2.0#629]
Currently it is not possible to differentiate between add to history and add to collection only the first one is supported. Will the second option "add to collection" be available in the future?

**Comment by michaldrabik** [comment]
Yes the Trakt's Collection is not supported in the app. This is meant for physical copies of movies for example and I do not plan on supporting it in the nearest future. Apologies.

**Comment by tobias-who** [comment]
Alright, thanks for clarification.
