### ISSUE TITLE
Showly syncing

### ISSUE THREAD

**Issue by Nadine0409** [michaldrabik/showly-2.0#632]
I have the showly app on my tablet but I decided to download it on my phone. It's not syncing correctly between devices. I have over 1000 shows on the app on my tablet but only 500 on my phone. How do I get it to sync correctly so all 1000 shows are on the app on my phone?

**Comment by michaldrabik** [comment]
You need to export your data from tablet into your Trakt.tv account and than use the same accoun to import on another device. This should get all the shows correct.
