### ISSUE TITLE
nav bar color in light theme

### ISSUE THREAD

**Issue by andsofine** [michaldrabik/showly-2.0#634]
navbar during light theme should be the same color as the bottom bar (it is black at the moment) 
![Screenshot_20220910-134341_1.png](https://user-images.githubusercontent.com/99369164/189479844-8ba421ff-207c-410f-8858-89d8a7b71ceb.png)

**Comment by michaldrabik** [comment]
Fixed. Navigation bar will be light one for users with Android 8.1 or higher (not supported below that)
