### ISSUE TITLE
Tract Sync Error

### ISSUE THREAD

**Issue by MidlajYH** [michaldrabik/showly-2.0#635]
Whenever i try to move a show from watch list to my shows it shows like this 👇🏻

![Screenshot_2022-09-12-13-35-49-153_com.michaldrabik.showly2.jpg](https://user-images.githubusercontent.com/85442225/189603863-1d709eaf-f31d-44fa-988b-4e16a4c4590f.jpg)

It's happening since yesterday.

**Comment by michaldrabik** [comment]
I think there were some Trakt server issues. Should be ok by now?

**Comment by MidlajYH** [comment]
I checked again, and it's working fine 👍🏻
