### ISSUE TITLE
[suggestion] sort order

### ISSUE THREAD

**Issue by rzuf84** [michaldrabik/showly-2.0#637]
Is there a possibility to add a function so that the newest episodes (premieres, new episodes) would appear at the top of the to-watch list for some time (regardless of the order of the rest of the currently watched series)?

**Comment by michaldrabik** [comment]
And to-watch list would be which screen exactly?

**Comment by rzuf84** [comment]
Specifically, I am referring to the progress widget and the progress tab. Something like a combination of recently viewed with most recent. The sorting looks similar in TV Time - at the top the latest episodes by premiere (say for a week from the broadcast date), then sorting by viewing date.
An example here (the first 2 items are freshly aired episodes, the rest are by viewing date):

<a href="https://postimg.cc/QHmLXqDx" target="_blank"><img src="https://i.postimg.cc/2SRC7HXv/Screenshot-20220921-094220-TV-Time.jpg" alt="Screenshot-20220921-094220-TV-Time"/></a><br/><br/>
<a href="https://postimages.org/" target="_blank"><img src="https://i.postimg.cc/g2VmSvf7/Screenshot-20220921-094313-One-UI-Home.jpg" alt="Screenshot-20220921-094313-One-UI-Home"/></a><br/><br/>
<br /><a href='https://postimages.org/pl/'>hosting stron www za darmo</a><br />

**Comment by michaldrabik** [comment]
I see now.
I guess this is a decent suggestion and I will consider adding such an option in sorting menu.

**Comment by rzuf84** [comment]
Thank you a lot!

**Comment by rzuf84** [comment]
Seems to be done! Thank you a lot!
