### ISSUE TITLE
UI  language changes after suspend resume  

### ISSUE THREAD

**Issue by blackholeearth** [michaldrabik/showly-2.0#643]
**Description:**
UI  language changes after suspend resume  .

**My settings:**
my phone lang is german.
Showly app lang is  English. (İn showly settings menu)

**Steps to reproduce:**
1)open showly app progress page .  UI is english (showly app Lang)
2) switch to another app.
3)  watch movie or  youtube 1 2 hour,
4)  switch to showly app.  UI is german (android phone language )

**Expected::**
 UI is always english (showly app Lang). Even after app minimized then switched back . 
suspend resume.

**Temp_Fix** : kill showly reopen App.

**note::**
You will not see this bug.
İf your phone lang is same with showply App language . 

Phone:  
Android 12 - samsung a12.

This also happened in my old phone: 
Android 8.1 -  moto g4

**Comment by blackholeearth** [comment]
https://github.com/michaldrabik/showly-2.0/blob/master/app/src/main/java/com/michaldrabik/showly2/App.kt

oncreate  : it is called for first run but.
.
OnResume : 
After minimize app reentering app, 
OnResume.  İscalled . OnCreate is not called in this situation.

So initLanguage() function is not called.

*How to fix: *
Need to call  initLanguage()   iniside OnResume.

**Comment by michaldrabik** [comment]
Hi, could you also specify device model and Android version?

**Comment by blackholeearth** [comment]
Android 12 - samsung a12.

Also this happened  with my old phone;
Android 8.1 -  moto g4

**Comment by michaldrabik** [comment]
@blackholeearth Working on some updates - feel free to test out this version and send some feedback:

[app-release.apk.zip](https://github.com/michaldrabik/showly-2.0/files/9794492/app-release.apk.zip)

**Comment by blackholeearth** [comment]
Error . Package clashes with the existing package Couldn't installed.

**Comment by michaldrabik** [comment]
Ah yeah sorry this is not Play Store signed. If you do not want to uninstall your current version no problem just need to wait till official release.

Thanks

**Comment by blackholeearth** [comment]
Since no way to export settings. . İ'll loose settings.

My pure android phone had multiple user account.
Like windows ,you have multiple users.

My current Phone  hasn't got this ability ( samsung a12).
------
Overcome this .
 İm trying parallel space apps ( 4 different app).

**Comment by blackholeearth** [comment]
Good job, mostly done. 👍👍

  There is one place thst hasnt been fixed. 
İts   ""airs in x days""

![showly_translation_v2](https://user-images.githubusercontent.com/7512105/198870172-8f0087ed-2a2f-4978-b028-99c2e0ef9c28.jpg)

**Comment by blackholeearth** [comment]
Here this place has wrong language

![Screenshot_20230613-133345_Showly](https://github.com/michaldrabik/showly-2.0/assets/7512105/351e0e3a-9df3-421f-bdb3-507b466a6ed2)

**Comment by blackholeearth** [comment]
İ think , this is fixed in  lastest version, released within 2 3 months.
