### ISSUE TITLE
[Feature Request] More detailed ratings

### ISSUE THREAD

**Issue by LukePet** [michaldrabik/showly-2.0#650]
Ability to insert more detailed ratings, for example 6.4, 7.5, 8.2, etc.

**Comment by LukePet** [comment]
> Why would this be an improvement over integer like rating ?

Right, it is a request to be evaluated well...the idea is to express more precise evaluations. Having the half votes (eg. 7.5) would not be bad. In any case, you must also comply with the rating systems already used around, so I would say that it is not such a priority request.

**Comment by michaldrabik** [comment]
This won't happen as Trakt does not support fraction ratings.

**Comment by LukePet** [comment]
Forget it, just ignore the request, it can be closed.
