### ISSUE TITLE
This version of the application not configured for billing through Google play.

### ISSUE THREAD

**Issue by Fatcakes** [michaldrabik/showly-2.0#653]
Trying to buy the one time deal, but get this error.

**Comment by michaldrabik** [comment]
Did you get the app from official Google Play Store or other source (like Github) ?

**Comment by Fatcakes** [comment]
@michaldrabik

**Comment by michaldrabik** [comment]
Yeah it can only work if you get it from official Google Play Store : (

**Comment by Fatcakes** [comment]
@michaldrabik then why not remove the option and the windows asking me to buy it on the git version? 🤣

**Comment by michaldrabik** [comment]
Still have FOSS version in the back of my head but STILL hasn't been able to get to it.
