### ISSUE TITLE
Login via Trakt.tv

### ISSUE THREAD

**Issue by bakinazik** [michaldrabik/showly-2.0#658]
i can't login via trakt.tv.
i guess the dev changed the all api.

![IMG_20221217_124210](https://user-images.githubusercontent.com/64368231/208235874-e8ed90b5-482f-4104-b779-6d5260aa098e.jpg)

**Comment by michaldrabik** [comment]
Trakt.tv had a breakdown recently. API is due to come back next week:

https://status.trakt.tv/

![image](https://user-images.githubusercontent.com/11537045/208235961-54c6c99c-2450-4740-aff9-55c70e4b929b.png)
