### ISSUE TITLE
[Feature] Poster option

### ISSUE THREAD

**Issue by Bamboozul** [michaldrabik/showly-2.0#663]
Instead of being forced to use the show poster (first season), we should be given the option of using the current season.

i.e : 

My Hero Academia

Replace the show poster (first season):

![s1](https://user-images.githubusercontent.com/101983929/209451717-252b5bc3-49d4-4a45-9a2b-cc45a5dba9ba.jpg)

With season 6 poster (current season):

![s6](https://user-images.githubusercontent.com/101983929/209451733-83105f05-5323-4797-a681-d6f49973ce3b.jpg)

**Comment by michaldrabik** [comment]
Custom posters/fanarts is already possible but it is reserved for Premium users.

**Comment by Bamboozul** [comment]
> Custom posters/fanarts is already possible but it is reserved for Premium users.

I'm not referring to custom posters or fanart because you'd have to change the posters for each show yourself and update them with each new season.

This option is available on the Trakt website, please see the images below for more information:

![Screenshot 2023-01-03 185259](https://user-images.githubusercontent.com/101983929/210403967-88251188-b351-4ff5-806f-ea99378a6b2c.png)
![Screenshot 2023-01-03 185335](https://user-images.githubusercontent.com/101983929/210403969-7ee63234-185b-4a7c-95c1-f8a10355bc3f.png)
![Screenshot 2023-01-03 185358](https://user-images.githubusercontent.com/101983929/210403973-19bbfbce-e2c1-41f5-87f0-7eba4b284af7.png)
![Screenshot 2023-01-03 185515](https://user-images.githubusercontent.com/101983929/210403978-23b36263-1721-4faf-9a1f-5f7511c0226c.png)

**Comment by Bamboozul** [comment]
This issue will be closed and a [new discussion](https://github.com/michaldrabik/showly-2.0/discussions/664) will begin to ensure that the repository rules are followed.
