### ISSUE TITLE
monet icon

### ISSUE THREAD

**Issue by andsofine** [michaldrabik/showly-2.0#670]
android 13 monet icon

**Comment by michaldrabik** [comment]
Hmm?

**Comment by michaldrabik** [comment]
Will try to add with the next update.

**Comment by michaldrabik** [comment]
Will be released with next update.

<img width="471" alt="image" src="https://user-images.githubusercontent.com/11537045/224657488-94d834d7-55a8-4fa2-9b4e-417c6aac8503.png">

**Comment by michaldrabik** [comment]
Should already be there long time ago. Got a screenshot maybe?

**Comment by bakinazik** [comment]
> Should already be there long time ago. Got a screenshot maybe?

![screenshot](https://github.com/michaldrabik/showly-2.0/assets/64368231/8b44eae7-8646-4dd1-86cc-f3df631d7fbf)

**Comment by bakinazik** [comment]
OS: crDroid Android 14, Poco F2 Pro
Showly Version: v3.33.3 (656) Play Store

**Comment by michaldrabik** [comment]
Sorry I misunderstood your original question. I thought this is only the app icon not the whole app we are talking about.

I have this in my backlog but cant give any promises when would I be able to pick it up. Lot of work to do besides it!
