### ISSUE TITLE
Incorrect info displayed on the "where to watch " bar

### ISSUE THREAD

**Issue by Toiletmason** [michaldrabik/showly-2.0#671]
My guess would be that the service or API isn't getting updated daily so there are instances where it says you can stream it from somewhere, but it's no longer on the service. Then if you confirm on justwatch.com you can see where it's currently available which is always correct. 

I'm not sure that this can be fixed, but I figured I'd mention it.

**Comment by michaldrabik** [comment]
The information comes from TMDB API which uses JustWatch to fetch their info. I suppose there are 2 layers of caching, on Showly side and TMDb side. That's why some results sometimes might be delayed a day or two.
