### ISSUE TITLE
Remembering your place on the artist's pages.

### ISSUE THREAD

**Issue by Toiletmason** [michaldrabik/showly-2.0#672]
When you're browsing artists' works and select one from the artist page, and then hit back to go to the list it completely resets the list instead of remembering your place and selection shows/movies.

<img src="https://tinypic.host/images/2023/02/19/Screenshot_20230217_195806_Showly.jpg" alt="Screenshot_20230217_195806_Showly.jpg" border="0" />

**Comment by michaldrabik** [comment]
Closing - duplicate #662
