### ISSUE TITLE
Tv show details page, cast is not refreshed . i updated cast at traktv

### ISSUE THREAD

**Issue by blackholeearth** [michaldrabik/showly-2.0#680]
İ added  tv show in  my showly   "the cliff"

İ saw that cast is wrong .
İ updated tmdb. Then reported traktv 
Now . i updated cast at traktv  website. İts new cast.

At showly app -> Tv show details page, cast is not refreshed !!?

Failed Attempt to fix:::
İ deleted cache, force stop restart. 
 Cast is still old data. 

Request::
İts wasteful update cast everytime i enter show details page.
 but can u put a button to refresh  Cast data or full data   ???

**Comment by Fooftilly** [comment]
It could be that Trakt API served you cached data because they maybe do not serve new data immediately.

**Comment by blackholeearth** [comment]
Huum okey.. i will come back in one week later.

 if its still old data. İ will report here the situation.

Thanks..
