### ISSUE TITLE
İf a shows all aired eps are watched, it goes into "returning & upcoming" section , but  this time last 2 ep is TBA.  it shows up in watching section (aka wrong)

### ISSUE THREAD

**Issue by blackholeearth** [michaldrabik/showly-2.0#685]
If you have an idea for a new feature or how to improve the app please use [Discussions](https://github.com/michaldrabik/showly-2.0/discussions) for that purpose.

**Describe the bug**
İf a show's all aired eps are watched, it goes into "returning & upcoming" section , but  this time last 2 ep is TBA.
 Thats why , it shows up in watching section (aka wrong)

**Expected behavior**
If all aired eps are watched , last 2 ep is tba(unaired).
It should be in the returning & upcoming section. 

**Screenshots**
![iMarkup_20230408_013054](https://user-images.githubusercontent.com/7512105/230687340-c41572cd-8aa5-472e-b8b6-a538474d4f90.jpg)

**Comment by michaldrabik** [comment]
As far as I can so for this show it should only have 10 episodes. So it seems like Trakt data is wrong:
https://www.imdb.com/title/tt22727856/episodes?year=2023&ref_=tt_eps_yr_2023

I'd suggest just reporting it so they update it.
