### ISSUE TITLE
Recently watched is backwards

### ISSUE THREAD

**Issue by hannes-dev** [michaldrabik/Showly-2.0#69]
hi, the new recently watched sort option sorts from oldest to newest, which isn't very convenient. 

![Screenshot_20200819-034732_Showly 20](https://user-images.githubusercontent.com/7892467/90582772-df0e7280-e1ce-11ea-86de-b43c3e7a8a10.jpg)
![Screenshot_20200819-034716_Opera](https://user-images.githubusercontent.com/7892467/90582776-e03f9f80-e1ce-11ea-8832-052ba2fbabb4.jpg)
![Screenshot_20200819-034646_Showly 20](https://user-images.githubusercontent.com/7892467/90582779-e170cc80-e1ce-11ea-87e7-ec2a85aed958.jpg)

**Comment by michaldrabik** [comment]
Hello,
after you start checking episodes as watched the items will sort properly.

**Comment by hannes-dev** [comment]
ah I see, it might make sense to reverse the list at the start too, since it is in proper order otherwise.

**Comment by michaldrabik** [comment]
By start you mean after Trakt import?

**Comment by hannes-dev** [comment]
Yes

**Comment by michaldrabik** [comment]
I took a look and made some updates. The last watched dates from Trakt will now be respected for the freshly imported shows.
The change will be included in the next update.
