### ISSUE TITLE
APK missing on Github for version 3.22.0

### ISSUE THREAD

**Issue by franco27** [michaldrabik/showly-2.0#704]
Hello

Usually I download the APK of your application on Github . To update 

Today I realize that a new version is available. 
I can't find the APK of this version on Github. Whereas I usually find her.

When I try to update , via the PlayStore, there is an error message and I cannot install the latest version.

thank you

**Comment by michaldrabik** [comment]
Forgot to push tag. Release will be available once the pipeline finishes in few mins.

**Comment by franco27** [comment]
Thank you for your reply. And all my compliments for your application. She is awesome. THANKS
