### ISSUE TITLE
[Feature Request] Add Paramount and Peacock in Network Filter. 

### ISSUE THREAD

**Issue by MidlajYH** [michaldrabik/showly-2.0#707]
![Screenshot_2023-05-21-13-51-49-066_com.michaldrabik.showly2.jpg](https://github.com/michaldrabik/showly-2.0/assets/85442225/e61b1afa-7aba-4f11-8a2d-299252727283)

**Comment by nzoba** [comment]
And Viki (Rakuten Viki) please

**Comment by skst** [comment]
Also, "HBO" should be renamed as "Max." ;)

Perhaps this should be in its own request, but it'd be great if networks could be multi-selected like Genres are.
