### ISSUE TITLE
Rotten Tomatoes Not Showing Properly 

### ISSUE THREAD

**Issue by Alexc26** [michaldrabik/showly-2.0#709]
It seems when looking at some TV shows, the rotten tomatoes score should appear, but for some reason doesn't.

The screenshots show the flash tv show as an example where there is actually a rotten tomatoes score, but doesn't show up on the Showly app. 

![Screenshot_20230601_194822_Showly](https://github.com/michaldrabik/showly-2.0/assets/5849605/988ea970-1118-4b22-9f09-a52fedf712ea)
![Screenshot_20230601_194835_Chrome](https://github.com/michaldrabik/showly-2.0/assets/5849605/52c001f0-3612-4c81-80ec-7f0d0a4b601f)

**Comment by MidlajYH** [comment]
#694
