### ISSUE TITLE
Add option to hide items which are on a trakt list from showing in the Discover tab.

### ISSUE THREAD

**Issue by Pouncingkitten** [michaldrabik/showly-2.0#711]
I would love the ability to hide items which are on a trakt list - similar to how you can hide collection - from appearing when browsing in the discover tab. Example:

I have a movie-queue list which are films I want to watch. When looking for new films to add to this list via the discover tab I would rather items in the movie-queue list be hidden.

**Comment by michaldrabik** [comment]
I have an idea of introducing Custom Lists based filter for both Progress and Discover, but no hard timeline on that just yet.
