### ISSUE TITLE
[Feature Request] Show rating on grid view

### ISSUE THREAD

**Issue by crxssed7** [michaldrabik/showly-2.0#715]
Pretty simple really. Show the rating in the grid view, just like the list views do (maybe in the top right of the poster?):

![Screenshot_20230613_230448_Showly](https://github.com/michaldrabik/showly-2.0/assets/48864420/5bdc6db6-417e-4ae5-ab5d-5f37af3e0892)

**Comment by michaldrabik** [comment]
Ratings are displayed in the rating related sortings (Top Rated and My rating)
