### ISSUE TITLE
[FEATURE REQUEST] Move the Calendar Toggle to a new Submenu Item

### ISSUE THREAD

**Issue by christopher-wilson** [michaldrabik/showly-2.0#717]
So, this is a usability suggestion. When you are Under Progress -> Movies/Shows, the _Progress, Calendar_ submenu could be improved to _Progress, Recent, Upcoming_ or _Progress, Upcoming, Recent_. and remove remove the toggling icon on the right.

The icon basically is adding another level of navigation that could be a menu items one step up.

I've attached mockups to show more clearly what I'm suggesting.
![Screenshot_20230615-115659](https://github.com/michaldrabik/showly-2.0/assets/4195720/a583c98d-c2e9-434c-9ef3-a1569dc592b6)
![Screenshot_20230615-115652](https://github.com/michaldrabik/showly-2.0/assets/4195720/36a32b6f-5532-483d-83a9-caf9ae1f52dd)

**Comment by michaldrabik** [comment]
Hello. I'm kind of leaving this space for future recently watched section.
You can still simply pull the list down when in Calendar for a fast switch (in addition to tapping icon)
