### ISSUE TITLE
Add Movies section

### ISSUE THREAD

**Issue by michaldrabik** [michaldrabik/showly-2.0#72]
- Split Discover screen into Shows/Movies tabs
- Add new, 4th tab "My Movies" next to My Shows
- Add Movies section in Watchlist
- Add Movies support in other application sections

**Comment by DurchEins** [comment]
How is it looking? Is this feature still being planned? 👀

**Comment by michaldrabik** [comment]
Sure it is but to be honest I have not started works on that. I'm hoping to kick it of in the beginning of December.

**Comment by michaldrabik** [comment]
A quick update for anyone interested. If everything goes well movies support will be released before Christmas. But I can't say its a done deal yet :)
