### ISSUE TITLE
Missing translations in Progress tab

### ISSUE THREAD

**Issue by Mannivu** [michaldrabik/showly-2.0#730]
**Describe the bug**
The app doesn't show the translated titles in the Progress tab. I'm not sure since when started to happen, but I am experiencing it with version 3.23.2 (537)

**Expected behavior**
The episode titles should be displayed in the selected language.

**Screenshots**
The next episode to watch is titled "Mind Your Body" wich was translated since some version ago.
![Screenshot_2023-08-24-09-24-47-968_com michaldrabik showly2-edit](https://github.com/michaldrabik/showly-2.0/assets/42747216/be51a7e5-713e-41bb-90d3-a5d0a3280bd7)

Clicking on "Dettagli" the details tab opens up and the titles is translated.
![Screenshot_2023-08-24-09-22-35-374_com michaldrabik showly2](https://github.com/michaldrabik/showly-2.0/assets/42747216/a5f4971f-e8f0-4f80-ba2b-20455190c4d5)

**Comment by michaldrabik** [comment]
This was already registered and will be fixed next update.

**Comment by michaldrabik** [comment]
Closing as it has been resolved and waiting for release.
