### ISSUE TITLE
"Add to my shows" by itself doesn't sync to Trakt

### ISSUE THREAD

**Issue by Victor239** [michaldrabik/showly-2.0#734]
**Describe the bug**
If I click "Add to my shows" button this doesn't get synced with Trakt. It'll only do so if I mark at least one episode watched. 

**Expected behavior**
Shows that are added should be automatically synced even if no episodes are marked as watched.

**Comment by Bamboozul** [comment]
It will be synced if you add it to your watchlist instead.

**Comment by Victor239** [comment]
Yes, but not the other button.

**Comment by michaldrabik** [comment]
This happens because Trakt does not have an option to add show without marked episodes into their progress. There need to be at least one.

It's an option exclusive to Showly.

**Comment by Victor239** [comment]
Ah I see. I'll try to keep this in mind then, maybe also put in in the README FAQ.
