### ISSUE TITLE
App redirects to Google Movies instead of Google TV

### ISSUE THREAD

**Issue by rk9qn3j** [michaldrabik/showly-2.0#735]
**Describe the bug**
I noticed the other day that the app doesn't redirect to the Google TV app, which has replaced the old Google Movies app.

**Expected behavior**
The app should redirect to Google TV instead.

**Screenshots**
![Screenshot_20230917-064526(1)](https://github.com/michaldrabik/showly-2.0/assets/18282546/b6cfff0c-b437-4841-b5c7-43de7cdbe7d5)
![Screenshot_20230917-064536(1)](https://github.com/michaldrabik/showly-2.0/assets/18282546/5fe9150f-d6e8-49eb-83c0-729ab99ae4e3)

**Comment by michaldrabik** [comment]
Updated link and will now open Google TV app properly. Will be released next update.
