### ISSUE TITLE
TV shows from "My shows" collection that I didn't mark watch progress in does not get synced with Trakt.tv

### ISSUE THREAD

**Issue by 32423d** [michaldrabik/showly-2.0#740]
If you have an idea for a new feature or how to improve the app please use [Discussions](https://github.com/michaldrabik/showly-2.0/discussions) for that purpose.

**Describe the bug**
TV shows from "My shows" collection that I didn't mark watch progress in does not get synced with my trakt.tv account as being part of my "My shows" collection. 

**Expected behavior**
TV shows that I have not marked any progress should appear in my "My shows" collection after logging into showly on a new install and reimporting my data through syncing with trakt.tv.

**Comment by michaldrabik** [comment]
@32423d Hello.

It is not really a "bug". 
Trakt.tv does not support a concept of added shows that has 0 episodes. You can notice that they can only trakt show's progress if at least 1 episode is marked. An option to have a show without marked episodes is exclusive to Showly and unfortunately there is not way to sync it with Trakt.
