### ISSUE TITLE
Search links just lookup first word of actor name

### ISSUE THREAD

**Issue by C-O-D** [michaldrabik/showly-2.0#749]
As the title says, when I start a lookup for an actor over one of the provided links, e.g. Google, DuckDuckGo or Wikipedia the search term consists just of the first word of the full name, so it's looking just for Kiele instead for Kiele Sanchez. IMDb and TMDB working fine strangely enough.
Any ideas what's going on?

**Comment by michaldrabik** [comment]
Hi!
I'm actually not able to reproduce it on my devices.
Maybe you could share some more info about your phone and Android version?

**Comment by C-O-D** [comment]
Well, I'm on MIUI 14.0.2 / Android 13 here on my Xiaomi Mi 10. Not so long ago everything worked, but I don't know what should have changed here either...

**Comment by C-O-D** [comment]
I just found out that the error comes from an app I have installed called 'Open Link With'.
After I uninstalled it everything is working again, so I'll get in touch with the developer in question.
Thanks for the feedback though.
