### ISSUE TITLE
Episode out of sync from release

### ISSUE THREAD

**Issue by larsjarred9** [michaldrabik/showly-2.0#756]
If you have an idea for a new feature or how to improve the app please use [Discussions](https://github.com/michaldrabik/showly-2.0/discussions) for that purpose.

**Describe the bug**
On the episodes of NCIS Sidney it shows that episode 5 has already been released meanwhile it releases on the 12th of December.

**Expected behavior**
It shouldn't show as released.

**Screenshots**
![Screenshot_20231210-233425.png](https://github.com/michaldrabik/showly-2.0/assets/31996561/b89a68a4-7d80-4481-a8ee-8fe65289fa2f)

**Comment by larsjarred9** [comment]
It appears that showly shows the initial launch date of the episode not the local availability which in this case would have been today.

**Comment by michaldrabik** [comment]
@larsjarred9 The dates are taken from Trakt so they should match. I believe they are indeed using original earliest launch dates so sometimes it might differ.

**Comment by larsjarred9** [comment]
Hi @michaldrabik still having the issue take a look at ncis Sidney ep 7 released yesterday in Australia yet it still says January.

**Comment by michaldrabik** [comment]
@larsjarred9 Hmm it says 21 December on my phone. Try opening NCIS Sydney show details and after the seasons data is loaded it should be correct?

**Comment by thornySoap** [comment]
Is it intended that Movies are shown with the original country release date?

**Comment by michaldrabik** [comment]
> Is it intended that Movies are shown with the original country release date?

Yes at this moment release date is not yet regionalised.
