### ISSUE TITLE
Wrong subscription price on the Premium page

### ISSUE THREAD

**Issue by tomeczeka** [michaldrabik/showly-2.0#762]
**Describe the bug**
Showly Premium page shows Premium subscription to be free.

**Expected behavior**
Instead of "free/month" and /year it should display actual prices like it used to.

**Screenshots**
![Screenshot_20231219-110831_Showly](https://github.com/michaldrabik/showly-2.0/assets/60844668/a990f4db-4c31-4921-bf2e-8b365e9df31c)

**Comment by michaldrabik** [comment]
@tomeczeka Does it also display wrong info when you tap it and Google Play dialog opens ?

**Comment by tomeczeka** [comment]
Yeah, it's there

**Comment by michaldrabik** [comment]
@tomeczeka Got a screenshot maybe? Thanks

**Comment by tomeczeka** [comment]
Attached

**Comment by tomeczeka** [comment]
Attached
![Screenshot_20231220-143551_Google Play Store](https://github.com/michaldrabik/showly-2.0/assets/60844668/6c1e4654-d2da-4e81-b03e-1e42ad42fdaa)

**Comment by michaldrabik** [comment]
@tomeczeka All right thanks. So all good there. Will be checking the app UI.

**Comment by tomeczeka** [comment]
> @tomeczeka All right thanks. So all good there. Will be checking the app UI.

Yeah sorry I meant "yeah _the correct price_ is there"
