### ISSUE TITLE
[Feature Request] Hide the season rating

### ISSUE THREAD

**Issue by johngarciava** [michaldrabik/showly-2.0#767]
The spoiler settings are great, however it seems like for shows, you can still see the rating for a whole season when you tap into them even if you haven't watched a single episode of that season and there doesn't seem to be an option in settings to be able to hide unwatched season ratings.

As a nice little extra thing, I think it would also be good to have a setting to hide actors in the movie/show details page for an unwatched movie/show as they can be a welcome surprise too.

**Comment by michaldrabik** [comment]
This will follow the episodes settings starting with next version. Closing. Thanks for reporting.
