### ISSUE TITLE
Add "to start" section

### ISSUE THREAD

**Issue by ad0726** [michaldrabik/Showly-2.0#77]
Add "to start" section to make a difference between shows you want to pause and those you want to start later.

**Comment by michaldrabik** [comment]
I think this is basically what can be achieved in "See Later" section currently is it not?

**Comment by ad0726** [comment]
Into "See Later", shows you have already started and you have put on hold and shows you have not started and you will start later are on the same place.
The idea is to have two sections: "To Start" and "To continued".

**Comment by michaldrabik** [comment]
I'll be passing on this one for now. 1st becasue I realy want to keep UI and UX as simple as possible and this will add another section to maintain that isn't that much requested at all.

 But most importantly I'm planning to add "**custom lists**" in the future. That will cover this case as well.
