### ISSUE TITLE
Android images not loading

### ISSUE THREAD

**Issue by RafaeldeGomesMonteiro** [michaldrabik/showly-2.0#772]
If you have an idea for a new feature or how to improve the app please use [Discussions](https://github.com/michaldrabik/showly-2.0/discussions) for that purpose.

**Describe the bug**
Images not loading. Tried restarting, reinstalling, nothing.

**Expected behavior**
Images should load I guess?

**Screenshots**
![Screenshot_20240127_223336_Showly](https://github.com/michaldrabik/showly-2.0/assets/106839063/399023de-208b-43c4-9736-268fc4d17e64)

**Comment by michaldrabik** [comment]
Could be some temp. network issues maybe? Have you tried using clear images cache option from app's settings?

**Comment by RafaeldeGomesMonteiro** [comment]
Definitely a temporary network issue. Wasn't working on my home network, but somehow worked fine on mobile. It's working on both now, so all good. Sorry about that :)
