### ISSUE TITLE
Getting notification about reached account limit despite having account with old limits

### ISSUE THREAD

**Issue by soredake** [michaldrabik/showly-2.0#775]
**Describe the bug**
I am getting notification about reached account limit despite having account with old limits.

**Expected behavior**
I should not receive this notification as according to this post https://twitter.com/trakt/status/1536751362943332352 I should have old limits as my account registered in 2014.

**Screenshots**
![Screenshot 2024-02-05 140325](https://github.com/michaldrabik/showly-2.0/assets/5204968/a187ff84-7bcc-440f-8b54-ef164e0ca70f)

**Comment by michaldrabik** [comment]
Hello. First lets check how many items you actually have on your Trakt watchlist:

How many are listed here?:
`https://trakt.tv/users/<YOUR_USERNAME>/watchlist`

**Comment by soredake** [comment]
> How many are listed here?:

1,520

**Comment by michaldrabik** [comment]
> > How many are listed here?:
> 
> 1,520

So it would seem that you should be covered. The error you pasted can only happen if the Trakt API returns an error code 420 which only suggests the limits error.

I must suggest writing to Trakt support first so they can confirm your account and that it should be eligible for 2000 watchlist items. Perhaps there is a mistake on their side. Not much the app can do here 🤔

**Comment by soredake** [comment]
> I must suggest writing to Trakt support first so they can confirm your account and that it should be eligible for 2000 watchlist items.

It definitely is, I can add items to watchlist absolutely fine with official site and android app. I will contact them and ask about this error.

**Comment by michaldrabik** [comment]
Please do and keep me posted. You might be able to still do so with official site and their app because they own them and they might be using different APIs compared to the ones 3rd party apps are using.

I will investigate more if needed.

**Comment by michaldrabik** [comment]
Also you may also try logging out and in again in the app and see if that changes anything. 

Regards.

**Comment by soredake** [comment]
Finally reported this issue to them, in the meantime, can this notification moved to separate channel like "api limit issue" so I can hide it? Sync works fine despite the message.

**Comment by soredake** [comment]
The answer I got:

![image](https://github.com/michaldrabik/showly-2.0/assets/5204968/b2d626b9-204b-4fe6-b809-dbbd08c6f74e)

**Comment by soredake** [comment]
> And when you add 1 item and run sync you are still getting the error but the sync works correctly? (new item appears in Trakt watchlist)

Sorry, I'll correct myself, importing from trakt works fine, exporting is not. Instant upload works fine at least.

**Comment by michaldrabik** [comment]
> Sorry, I'll correct myself, importing from trakt works fine, exporting is not. Instant upload works fine at least.

Yes I meant you have 1800 items in the Showly watchlist. You add movie to watchlist in the app and run normal sync (not instant upload)

**Comment by soredake** [comment]
With normal sync export, I don't see the added movie in watchlist.

**Comment by michaldrabik** [comment]
Introduced change that should fix this. Will be released with next update.
