### ISSUE TITLE
İ deleted and reinstalled the github release 3.31.  not everything is synced down in to the app

### ISSUE THREAD

**Issue by blackholeearth** [michaldrabik/showly-2.0#780]
**Describe the bug**
**Short::**
İn fresh install,  
İ Pressed import/syncNow button. 
showly doesn't fetch all hidden shows.
 1st time, it was  93 hidden show.
 Not retrieved from trakt.

İ deleted reinstalled app again,
2nd time, it was 5 hidden show. 
 Not retrieved from trakt.

*Note:* while app was syncing, i opened discover page .  pressed hide anticipated , hide collection 

**Long:**
İ deleted and reinstalled the github release 3.31  not everything is synced down in to the app.

And half of the hidden shows is not synced down to the fresh installed app.

İ pressed move to hidden for all of them.
Luckily i have added them to  list called
" status: Dropped ".
İ hid them again , checking against the custom list.

 probably they are hidden in the web site.

But fresh installed app couldnt fetch some of hidden shows .

İ checked the hidden shows list, there are some shows in there. But i had to hide  93 shows.

All of that 93shows had some watched episodes.
İ have watched them 1 or 2 years ago .
(Not recently watched)

İ  have 257 shows total.(in app stats page)

---------

There is a show called legion 
İn app before delete ;
its progress is 
S1 s2 watched - s3 no watched. 
At the Freshly installed app. 
Progress is no episode iswatched.
(İts in the hidden) 

**Edit:** 
goddamn, because those 93 hidden shows popped up  İn progress.
1) İ have pressed move to hidden.
2) Said yes to message."remove progress. are u sure? "

(That legion show is one of them)
All 93 has 0 episodes watched .
that orange colored progress bar has gone to Zero...

**Edit2:** 
oh my god ,  since i realized instant upload is off.
İ deleted , reinstalled app.  Logged in . Synced.

Only 1 show s progress is lost. Which i recently reported it to tmdb for incorrect data..

And , This time only  "5 hidden show" has popped up in progress.

All safe 😎👍.... 
But ,Such a nerve wrecking experience. 😱😨
İt Was roller coaster..

-----------
How do i know, that 5 hidden is definitely hidden ,for sure? 
Because i added them in custom list called "dropped" 

**Expected behavior**
1) App should properly fetch the hidden shows list
2) After that it should either query the trakt hidden show count or sth. 

**Screenshots**

**Comment by michaldrabik** [comment]
Not sure if I got all that but the main thing to ensure is what you have on www.trakt.tv hidden section. After clean install and import this hidden section is fetched first and only shows that are not present are added into "My Shows"

**Comment by blackholeearth** [comment]
İ ve inspected  trakt settings hidden item.
Those hidden items are there .
640 hidden show. ( Counted them1 by 1 ,Such a chore on phone)

İ made sure , Verified the 10 shows hidden in website.
But fresh installed app shows them in progress.
İts more than 10 , 


But the fresh installed showly puts them in progress/myShows .

Maybe u have hard limit to fetch 500 hidden items ??

-------

1)
İve installed another client . Janthoine show tracker.
İt fetches all shows in the hidden section without a problem.

2) i ve installed cinexplore, it fetched all hidden shows (which has some progress)  without problem.

**Comment by michaldrabik** [comment]
If I remember correctly there might actually be a limit there for hidden items import that might cause trouble. Ill check and if there is I will rework it. Probably nobody ever before had that many hidden items :)

**Comment by michaldrabik** [comment]
Probably found the casue and with version 3.31.0 all your hidden items should be fetched properly now. You can give it a go.

**Comment by blackholeearth** [comment]
İt works thankss ....

İn the app,  
All those shows supposed to be hidden are hidden from the progress..👍👍

These hard limits are dangerous.

İ Really wonder whats gonna happen when hit
1000 hidden shows??
Or 2000 hidden shows??

İ heard trakt has list limits

**Comment by michaldrabik** [comment]
Limits does not touch hidden items actually: https://github.com/trakt/api-help/discussions/350?ts=2

Now no matter how many hidden items you have they will be fetched proeprly
