### ISSUE TITLE
Hidden shows progress is not exported when i press  sync now??

### ISSUE THREAD

**Issue by blackholeearth** [michaldrabik/showly-2.0#781]
**Describe the bug**

İ have 90 shows in the hidden list which have progress 
Whrn i pressed move to hidden,
İt said message  "remove from progress, are u sure ? "
İ said yes . 
Now all hidden shows progress is deleted on website.

But app has them locally.
So i wantto upload the progress back into trakt website..

When i press sync now.
They are not exported to trakt.

**Expected behavior**
İ expected it to sync  hidden shows progress to up to track .

İf you dont want to it sync button.
A seperete  button for  sync hidden now .
Will be appreciated.

User can do it manually for disaster scenarios.

**Screenshots**

**Comment by michaldrabik** [comment]
When you "remove from progress, are u sure?" the local watched episodes for the show are also removed. That's why when you export they are not exported.

It's always been like that and nothing has changed recently.

**Comment by blackholeearth** [comment]
New question?

İ have custom list name is dropped .
İt has 90 tv shows.
All of them is marked as hidden.

When i press sync now .
İt should export local show progress to trakt

But it doesn't sync up.

İs this expected behavior??

İ can add a video of this process.

**Comment by blackholeearth** [comment]
İ understand why  sync local to trakt doesn't work.

Because those shows in custom list, their progress is made a  long time ago.( 6months ago)
When i press sync.  Those are ignored.

Only new  changes (made in last 3 5 days) are synced up.

-----
İ am entering  shows 1by1 , and  selecting the  same episodes.
This is triggering instant  Sync notification.

İ checked website now . its getting the same data as app.

Painful but ill get those 90shows progress back.

------
What iam doing manually 1by1.
İ expected this from the app sync now button.


[✓] export local to trakt
(Sync now)
