### ISSUE TITLE
V3.33 is installing as v3.31.1

### ISSUE THREAD

**Issue by 0-BlackSpectrum-0** [michaldrabik/showly-2.0#792]
If you have an idea for a new feature or how to improve the app please use [Discussions](https://github.com/michaldrabik/showly-2.0/discussions) for that purpose.

**Describe the bug**
No matter how many times I install the latest v3.33 it's still the version 3.31.1

**Expected behavior**
After installing v3.33 the version should change to v3.33 but it remains the same v3.31.1

**Screenshots**

![Screenshot_20240302-155247_Package installer.png](https://github.com/michaldrabik/showly-2.0/assets/79910450/d8f8b8f1-1cf6-4e1f-8546-1ceee489d659)

![Screenshot_20240302-155254.png](https://github.com/michaldrabik/showly-2.0/assets/79910450/cb56eae0-6832-4e02-a3a2-605b91d0ce9b)

![Screenshot_20240302-155340_Showly.png](https://github.com/michaldrabik/showly-2.0/assets/79910450/91bada22-5643-4ee8-8b1c-113f09980b79)

**Comment by 0-BlackSpectrum-0** [comment]
Btw I'm running android 11 one ui 3.1 if that helps

**Comment by michaldrabik** [comment]
Oh, its just a name bug. But if the code is 633 then its the actual latest version.

**Comment by 0-BlackSpectrum-0** [comment]
> Oh, its just a name bug. But if the code is 633 then its the actual latest version.

Ok, thanks it's just I use Obtainium for fetching  updates from github so it kept showing me to update everytime I installed it.
