### ISSUE TITLE
Searching exact title comes at the bottom of the results!    

### ISSUE THREAD

**Issue by blackholeearth** [michaldrabik/showly-2.0#794]
**Describe the bug**
1)  search  "kanatsız kuşlar" .
     * its TR show.
2)  the result i want  is at the bottom .

 The exact title is the last one in the search results. ??
Whereas lots of totally unrelated show comes above of it.??

**Expected behavior**
İ expect it to come at top as 1st one in search results 

**Note:**
Maybe. sorting by Rank isn't the right answer, if the show is not popular .

İs there sort by relevance  in the api?

**Comment by michaldrabik** [comment]
Yeah, seems like there has been some changes in Trakt search and will need to adjust

**Comment by blackholeearth** [comment]
Checked the v34.  same result with website.  👍Thanks.
