### ISSUE TITLE
"Copied to clipboard" alert partially obscured

### ISSUE THREAD

**Issue by Mannivu** [michaldrabik/showly-2.0#795]
**Describe the bug**
When copying the name of a person the "Copied to clipboard" alert is partially obscured by person's picture.

**Expected behavior**
The alert should be completely visible. 

**Screenshots**
![Screenshot_2024-03-04-11-36-26-834_com michaldrabik showly2](https://github.com/michaldrabik/showly-2.0/assets/42747216/3b5f1b27-639d-4490-85ed-ed471702335f)

**Comment by michaldrabik** [comment]
Could you share your device model?

**Comment by michaldrabik** [comment]
Thanks. Cant reproduce it on my devices but I do not own Xiaomi. Made potential fix in the dark so with next release you can test it out and let me know if it worked.
https://github.com/michaldrabik/showly-2.0/commit/a71b0bedb36e9a63b60dfeb386fc848c24404fe7

**Comment by Mannivu** [comment]
Thanks, I'll let you know.

**Comment by michaldrabik** [comment]
Feel free to try with 3.35 release

**Comment by Mannivu** [comment]
While I wait for 3.35 I've discovered that in 3.33.3 the bug isn't present while using dark mode
![Screenshot_2024-03-23-23-23-43-730_com michaldrabik showly2](https://github.com/michaldrabik/showly-2.0/assets/42747216/ad3194ec-ed47-4ff8-b93a-3b9da9a5a3fb)

**Comment by Mannivu** [comment]
After the update, the "Copied to clipboard" is no more obscured. Thank you.
