### ISSUE TITLE
UI is not clear

### ISSUE THREAD

**Issue by 002gRTEah3mRYH** [michaldrabik/showly-2.0#798]
Hello,

Why the app use "Collection" tab for history or watched on Trakt ?

Collection on Trakt is what I'm owning, not what I've whatched or planned to watch.
And also in Collection tab, it's call Movies > My movies, and not Movies > Watched

There should be a 4th tab, like Discover/Progress/History/Collection

This is really weird or did I miss something ?

**Comment by michaldrabik** [comment]
To clarify Showly was not meant to be 1 to 1 client of Trakt. The integration was added later. So this is why you can see some naming "clashes" but it's been like this since day 1.
