### ISSUE TITLE
Crash when scrolling history tab

### ISSUE THREAD

**Issue by sherpajosh** [michaldrabik/showly-2.0#804]
The app crashes when I try to scroll the history tab.

**Comment by michaldrabik** [comment]
Unfortunately for OSS version I dont have insight into Crashlogs :( Does it happen only after you scroll for a bit?

**Comment by sherpajosh** [comment]
Yup, I can scroll maybe 2-3 lines then it force closes. If I re-open the app and try do it again I get the pop up saying the Showly keeps stopping.

**Comment by michaldrabik** [comment]
Is your in app language English or different?

**Comment by sherpajosh** [comment]
English

**Comment by sherpajosh** [comment]
Clearing cache and storage seems to have fixed it.
