### ISSUE TITLE
Shows-> Progress is empty even if there are shows I'm currently watching 

### ISSUE THREAD

**Issue by frankieta** [michaldrabik/showly-2.0#805]
**Describe the bug**
The Shows-> Progress tab displays no shows even if I'm currently watching several of them. The ones I'm watching aren't paused and are added as My Shows.

Version is 3.34.2 (662)

**Expected behavior**
I expect to see the remaining episodes of the shows I'm currently watching but not finished.

**Screenshots**
Empty Shows tab:
![Screenshot_20240328_220321_Showly](https://github.com/michaldrabik/showly-2.0/assets/6009920/b2c40578-95f2-4e8b-86a9-85cef0401a99)

Proof I'm watching a show:
![Screenshot_20240328_220408_Showly](https://github.com/michaldrabik/showly-2.0/assets/6009920/f4df5c27-a85e-4de5-91cf-28ca78e54bdc)

**Comment by michaldrabik** [comment]
@frankieta Seems like you run into some new bug that activated Upcoming filter in progress and hid it completely. I will need to check it out. In the meantime I think the easiest way would be to just clear the app data or reinstall. Hopefully it is not big of an issue for you.

**Comment by michaldrabik** [comment]
@frankieta What happened probably is that you had Upcoming filter active while you turned off Upcoming section in the settings. Try:

1. Go to settings and then set "Upcoming Section" to anything else than "Disabled"
2. Open Progress screen
3. Turn off Upcoming filter (will not be red color)
4. You can now disable Upcoming section again via Settings.

That should fix it.
I will address this bug in next update.

**Comment by michaldrabik** [comment]
Fixed and will be in next release.
