### ISSUE TITLE
Play Store listing translation into Spanish

### ISSUE THREAD

**Issue by michaldrabik** [michaldrabik/showly-2.0#81]
Looking for help with **Spanish** translation for following descriptions:

1. **Max 50 chars**
> Showly 2.0 - Open Source TV Shows Tracker

2. **Max 80 chars**
> Showly 2.0 is modern, slick, open-sourced TV Shows tracking app.

3. **Max 4000 chars**
> PLEASE NOTE: THIS APP IS NOT MEANT FOR WATCHING TV SHOWS.
> 
> Showly 2.0 is an open-source, modern TV Shows tracking app that works with Trakt.tv service.
> 
> Features:
> - Follow the most trending and anticipated TV shows
> - Refine discover feed to match your personal preferences
> - Next episode tracking
> - Receive optional notifications and reminders of new episodes and seasons premieres
> - Trakt.tv import/export
> - Manage your current shows and shows you want to see in the future
> - View detailed show information and read users comments
> - Statistics
> - Widgets
> - Small download size: only ~3 MB
> 
> Showly 2.0 allows to keep track of all your shows including those on ABC, NBC, CBS, Fox, The CW, Netflix, Hulu, Amazon, HBO, MTV, Bravo, BBC, Channel 4, ITV, Sky and more!
> 
> Showly 2.0 is an open source project.
> Feel free to visit project's site and report any issues at: 
> https://github.com/michaldrabik/showly-2.0
> 
> Showly 2.0 is powered by Trakt.tv and TMDB services.

**Comment by techeverri** [comment]
| English | Spanish |
|---|---|
| Showly 2.0 - Open Source TV Shows Tracker | Showly 2.0 - Herramienta de código abierto para llevar registro de los programas de televisión que estás viendo |

**Comment by techeverri** [comment]
| English | Spanish |
|---|---|
| Showly 2.0 is modern, slick, open-sourced TV Shows tracking app. | Showly 2.0 es una herramienta moderna, elegante y de código abierto para llevar registro de los programas de televisión que estás viendo |

**Comment by techeverri** [comment]
### English

> PLEASE NOTE: THIS APP IS NOT MEANT FOR WATCHING TV SHOWS.
> 
> Showly 2.0 is an open-source, modern TV Shows tracking app that works with Trakt.tv service.
> 
> Features:
> 
> * Follow the most trending and anticipated TV shows
> * Refine discover feed to match your personal preferences
> * Next episode tracking
> * Receive optional notifications and reminders of new episodes and seasons premieres
> * Trakt.tv import/export
> * Manage your current shows and shows you want to see in the future
> * View detailed show information and read users comments
> * Statistics
> * Widgets
> * Small download size: only ~3 MB
> 
> Showly 2.0 allows to keep track of all your shows including those on ABC, NBC, CBS, Fox, The CW, Netflix, Hulu, Amazon, HBO, MTV, Bravo, BBC, Channel 4, ITV, Sky and more!
> 
> Showly 2.0 is an open source project.
> Feel free to visit project's site and report any issues at:
> https://github.com/michaldrabik/showly-2.0
> 
> Showly 2.0 is powered by Trakt.tv and TMDB services.

### Spanish

TENGA EN CUENTA: ESTA APLICACIÓN NO ES PARA VER PROGRAMAS DE TELEVISIÓN.

Showly 2.0 es una herramienta moderna para llevar registro de los programas de televisión que estás viendo que funciona con Trakt.tv

Características:

- Sigue los programas de televisión más populares y esperados
- Descubre series que coinciden con tus preferencias personales
- Entérate de la fecha y hora de emisión del próximo episodio
- Recibe notificaciones opcionales y recordatorios de nuevos episodios y estrenos de temporadas.
- Sincronización con Trakt.tv
- Registre sus programas actuales y los programas que desea ver en el futuro
- Vea información detallada del programa y lea los comentarios de los usuarios
- Estadísticas
- Widgets
- Tamaño de descarga pequeño: solo ~3 MB

Showly 2.0 permite realizar un seguimiento de todos sus programas, incluidos los de ABC, NBC, CBS, Fox, The CW, Netflix, Hulu, Amazon, HBO, MTV, Bravo, BBC, Channel 4, ITV, Sky y más.

Showly 2.0 es un proyecto de código abierto.
No dude en visitar el sitio del proyecto e informar cualquier problema en:
https://github.com/michaldrabik/showly-2.0

Showly 2.0 funciona gracias a Trakt.tv y TMDB.

**Comment by michaldrabik** [comment]
@techeverri Big thanks for these!

Unfortunately numbers 1 nad 2 are max. length limited in PlayStore. My apologies I forgot to mention this initially.
They would need to be shortend to match the limit.

**Comment by techeverri** [comment]
| English | Spanish |
|---|---|
| Showly 2.0 - Open Source TV Shows Tracker | Showly 2.0 - Gestor de programas de TV open-source |

**Comment by techeverri** [comment]
| English | Spanish |
|---|---|
| Showly 2.0 is modern, slick, open-sourced TV Shows tracking app. | Showly 2.0 es una app moderna, elegante y open-source para gestionar programas de TV |

I couldn't make this one shorter (84/80)

**Comment by techeverri** [comment]
I tried my best to shorten the sentences. I feel a lot of info is lost in the translation because of the max length limit.

Hope it helps anyway 👍

**Comment by michaldrabik** [comment]
Thank you. I think we can just skip a word in Spanish translation then. Does this make sense in Spanish?

Showly 2.0 is modern, open-source TV Shows tracking app.
**Showly 2.0 es una app moderna, open-source para gestionar programas de TV**

**Comment by techeverri** [comment]
It looks ok although I wouldn't use "open-source" in Spanish but I had to use it for https://github.com/michaldrabik/showly-2.0/issues/81#issuecomment-716068504

**Comment by michaldrabik** [comment]
I think I'm okay for dropping open-source in translations if that does not feel right.
How about:

1. Showly 2.0 - Modern TV Shows Tracker

2. Showly 2.0 is modern, slick TV Shows tracking app.

?

**Comment by techeverri** [comment]
I meant, I wouldn't use "open-soruce" in the Spanish translation but rather what I did in https://github.com/michaldrabik/showly-2.0/issues/81#issuecomment-712719006 (that is too long)
The original sentence in English sounds just fine 👍 

Sorry for the confusion 😅

**Comment by michaldrabik** [comment]
Yes but for the sake of Spanish translation I'll drop the open source word. We can translate without it :)

**Comment by techeverri** [comment]
In that case, I could be as follows


| English (without open source) | Spanish (_77/80_) |
|---|---|
| Showly 2.0 is modern, slick TV Shows tracking app. | Showly 2.0 es una aplicación moderna, elegante para gestionar programas de TV |

**Comment by michaldrabik** [comment]
Thank you. I'm currently working on adding full language translations support in the app itself. If you might want to help with Spanish let me know (this will be a little bit more work though :) )

**Comment by techeverri** [comment]
I would more than happy to help 👍
Just let me know.

Are you planning to use [Transifex](https://www.transifex.com/) (free for opens source projects) or something similar?

Using a platform to handle the translations would be easier for everyone involved and of course better than GitHub issues 😅

**Comment by michaldrabik** [comment]
Never used this one. I will check it out. Otherwise I will prepare Google Sheet which should also work well.

**Comment by techeverri** [comment]
There are several translation platform apart from Transifex that offer full-featured free plans for open source projects

I can share a list of you want 👍

**Comment by michaldrabik** [comment]
@techeverri Transifex looks quite good. I've set up a project and created first 2 resources to test it out. 

Feel free to request invite here: https://www.transifex.com/showly-20

**Comment by techeverri** [comment]
Awesome :+1:

The link to request the invite doesn't seem to work though

**Comment by michaldrabik** [comment]
@techeverri Seems to be working fine... It opens a project page and there is a button there:
![obraz](https://user-images.githubusercontent.com/11537045/97268818-c1900180-182c-11eb-83e8-802052f90886.png)

Is it broken? It brings me to login page.

**Comment by techeverri** [comment]
I just tried once more using Incognito mode. It worked 👍 
_Request to join the team (Spanish) sent_

**Comment by michaldrabik** [comment]
Thanks for translations. I like transifex and we can stay with that. Later I will add all necessary resources and create relevant Github issues for anyone who might want to help as well.

**Comment by techeverri** [comment]
Yeah, Transifex is very cool 👍
