### ISSUE TITLE
Unable to access paid features in OSS version.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [michaldrabik/showly-2.0#816]
#### **Describe the bug**

There's no way for me to access paid features, because there's no way to pay.

#### **Expected behavior**

I expect them to be available, or a payment method to be available.

#### **Screenshots**

> ![Screenshot_20240426-225148](https://github.com/michaldrabik/showly-2.0/assets/42837531/4a8771a0-1a69-4e59-899c-73cb5b948bd7)

**Comment by michaldrabik** [comment]
Since all payments are connected with Google and Google Services it's just not possible in OSS version. To have that download PlayStore version of the app :)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/michaldrabik/showly-2.0/issues/816#issuecomment-2080398456

@michaldrabik, I can't. I don't have the Play Store.
