### ISSUE TITLE
Play Store listing translation into German

### ISSUE THREAD

**Issue by michaldrabik** [michaldrabik/Showly-2.0#82]
Looking for help with **German** translation for following descriptions:

1. **Max 50 chars**
> Showly 2.0 - Open Source TV Shows Tracker

2. **Max 80 chars**
> Showly 2.0 is modern, slick, open-sourced TV Shows tracking app.

3. **Max 4000 chars**
> PLEASE NOTE: THIS APP IS NOT MEANT FOR WATCHING TV SHOWS.
> 
> Showly 2.0 is an open-source, modern TV Shows tracking app that works with Trakt.tv service.
> 
> Features:
> - Follow the most trending and anticipated TV shows
> - Refine discover feed to match your personal preferences
> - Next episode tracking
> - Receive optional notifications and reminders of new episodes and seasons premieres
> - Trakt.tv import/export
> - Manage your current shows and shows you want to see in the future
> - View detailed show information and read users comments
> - Statistics
> - Widgets
> - Small download size: only ~3 MB
> 
> Showly 2.0 allows to keep track of all your shows including those on ABC, NBC, CBS, Fox, The CW, Netflix, Hulu, Amazon, HBO, MTV, Bravo, BBC, Channel 4, ITV, Sky and more!
> 
> Showly 2.0 is an open source project.
> Feel free to visit project's site and report any issues at: 
> https://github.com/michaldrabik/showly-2.0
> 
> Showly 2.0 is powered by Trakt.tv and TMDB services.

**Comment by DurchEins** [comment]
1. Showly 2.0 - Open Source Serien Tracker

2. Showly 2.0 ist eine moderne & schlanke Open-Source-Tracking-App für deine Serien.

3. ACHTUNG! MIT DIESER APP KANN MAN KEINE SERIEN ODER FILME STREAMEN!
Showly ist eine moderne Open-Source App um den Stand deiner Serien mit Hilfe von Trakt.tv festzuhalten.
Features: 

* Folge den angesagtesten TV-Shows, Serien & Filmen.
* Verfeinere den Discovery-Feed entsprechend deiner persönlichen Vorlieben.
* Die nächste Folge tracken.
* Erhalte optionale eine Erinnerungen über neue Episoden und Staffeln.
* Importiere/Exportiere deine Daten mit Trakt.tv
* Verwalte deine aktuellen Serien & Filme & nutz für zukünftige Serien das Lesezeichen.
* Sieh dir detaillierte Show-Informationen an & ließ die Kommentare anderer Nutzer.
* Statistiken! 
* Nutze auf dem Homescreen ein Widget.
* Nur kleine Appgröße: ~3MB

Mit Showly 2.0 kannst du Serien und Filme von vielen verschiedenen Anbietern tracken. Unter anderem sind ABC, NBC, CBS, Fox, The CW, Netflix, Hulu, Amazon, HBO, MTV, Bravo, BBC, Channel 4, ITV, Sky mit dabei, aber auch noch viele weitere Streaminganbieter. 
Showly 2.0 ist ein Open Source Projekt!
Fühl dich frei dir die Projektseite anzuschauen und ggf. Fehler zu melden oder mitzuwirken:
https://github.com/michaldrabik/showly-2.0
Showly 2.0 wird von Trakt.tv- und TMDB-Diensten unterstützt.

**Comment by michaldrabik** [comment]
@DurchEins Much appreciated!
