### ISSUE TITLE
"Next Episode" section slightly clips the date text at the bottom

### ISSUE THREAD

**Issue by skst** [michaldrabik/showly-2.0#825]
**Describe the bug**
The characters of the last line of the "Next Episode" section are slightly clipped--maybe 2-3 pixels.

In case it's relevant, my phone is a Moto g Power 2023 and the screen is 2400x1080.

Obviously, this is a super-low priority. I can't imagine any issue with a lower priority. On the other hand, it's probably a super-easy fix. ;-)

**Expected behavior**
No clipping. :-)

**Screenshots**
Screenshot showing the issue. It's most noticeable in characters that have descenders, such as the "y"s and the commas.

![Screenshot_20240526-195345](https://github.com/michaldrabik/showly-2.0/assets/74487/9066000a-6abe-44bb-91d4-2f30fddb631c)

**Comment by michaldrabik** [comment]
I'll be honest not sure what to do about it - on my test devices I can't reproduce it : ) but I do not have Motorola specifically 🤔

**Comment by skst** [comment]
You're right! My font is one step larger (it's not percentages on this phone) and when I reset it to defaults, the font is no longer clipped.

FWIW, the screen is 1080x2400.

**Comment by michaldrabik** [comment]
Yeah with font size I am actually able to reproduce it so will try to adjust and fix that bug.
