### ISSUE TITLE
 Play Store listing translation into French

### ISSUE THREAD

**Issue by michaldrabik** [michaldrabik/showly-2.0#83]
Looking for help with **French** translation for following descriptions:

1. **Max 50 chars**
> Showly 2.0 - Open Source TV Shows Tracker

2. **Max 80 chars**
> Showly 2.0 is modern, slick, open-sourced TV Shows tracking app.

3. **Max 4000 chars**
> PLEASE NOTE: THIS APP IS NOT MEANT FOR WATCHING TV SHOWS.
> 
> Showly 2.0 is an open-source, modern TV Shows tracking app that works with Trakt.tv service.
> 
> Features:
> - Follow the most trending and anticipated TV shows
> - Refine discover feed to match your personal preferences
> - Next episode tracking
> - Receive optional notifications and reminders of new episodes and seasons premieres
> - Trakt.tv import/export
> - Manage your current shows and shows you want to see in the future
> - View detailed show information and read users comments
> - Statistics
> - Widgets
> - Small download size: only ~3 MB
> 
> Showly 2.0 allows to keep track of all your shows including those on ABC, NBC, CBS, Fox, The CW, Netflix, Hulu, Amazon, HBO, MTV, Bravo, BBC, Channel 4, ITV, Sky and more!
> 
> Showly 2.0 is an open source project.
> Feel free to visit project's site and report any issues at: 
> https://github.com/michaldrabik/showly-2.0
> 
> Showly 2.0 is powered by Trakt.tv and TMDB services.

**Comment by esQmo** [comment]
Hello, I would like to help. What can I do?

**Comment by michaldrabik** [comment]
@esQmo Simply respond in a comment. Like here: #82 

Thanks

**Comment by esQmo** [comment]
1. Showly 2.0 - Gestionnaire des séries télé Open source
2. Showly 2.0  est une application de suivi des séries télé moderne, élégante et open-source.

Caractéristiques:
- Suivi des séries télé les plus tendances et les plus attendues
- Affinage le flux de découverte en fonction de préférences personnelles
- Suivi d'épisodes suivants
- Réception des notifications et des rappels facultatifs des nouveaux épisodes et des premières des saisons
- Importation/exportation de données Trakt.tv
- Gestion des séries télé actuelles et des séries télé à regarder à l'avenir
- Affichage des informations détaillées sur les séries télé et lecture des commentaires des utilisateurs
- Statistiques
- Widgets
- Taille minimale de téléchargement: ~3 Mo seulement

Showly 2.0 permet de garder une trace de toutes vos émissions, séries télé, y compris celles sur ABC, NBC, CBS, Fox, The CW, Netflix, Hulu, Amazon, HBO, MTV, Bravo, BBC, Channel 4, ITV, Sky et plus encore!

Showly 2.0 est un projet Open source.
N'hésitez pas de visiter le site du projet et signaler tout problème:
https://github.com/michaldrabik/showly-2.0

Showly 2.0 est alimenté par les services Trakt.tv et TMDB.

**Comment by michaldrabik** [comment]
@esQmo Thank, much appricated. 

Could you also add this lines? 

> PLEASE NOTE: THIS APP IS NOT MEANT FOR WATCHING TV SHOWS.
> Showly 2.0 is an open-source, modern TV Shows tracking app that works with Trakt.tv service.

**Comment by esQmo** [comment]
Welcome

**Comment by esQmo** [comment]
A NOTER QUE CETTE APPLICATION NE PERMET PAS LE VISIONNAGE DES SÉRIES TÉLÉVISÉES

Showly 2.0 est une application de suivi des séries télé moderne, élégante et open-source qui fonctionne avec le service Trakt.tv.
