### ISSUE TITLE
Problems with non-English search

### ISSUE THREAD

**Issue by whghjyh** [michaldrabik/showly-2.0#832]
I am a Chinese user.I want to know when I search for an item, does its information come from tmdb?I have used many other similar apps and love showly, but its search function is so bad, at least for Chinese users.For example, when I want to search for "Evangelion"，In Chinese it is "新世纪福音战士"，When I typed this, there were supposed to be a lot of results, including TV and movies, but that didn't happen.However, it works on the tmdb website or in other software that uses the tmdb database, such as seriesguide and moviebase.Such a problem occurs repeatedly when entering Chinese terms, and I don't know if the same is true for other non-English languages, but at least it's inaccurate to use Chinese search.I really hope you can solve these problems. In fact, since the previous versions of the app were updated with Chinese translations, I have recommended it to many of my friends, and they also like it very much.
  Finally, I sincerely thank you and your team for your efforts to develop this excellent app.

**Comment by michaldrabik** [comment]
Thanks. I am just a single developer not a team : )

Can't vouch for the other apps but Showly currently is using Trakt as the main source. In that case if the translated title appears in their API it will be listed in the search.

So in case of your example 新世纪福音战士 it will give 

![image](https://github.com/user-attachments/assets/a65db049-d9d3-4e60-83f2-252d1ccad7fe)

(website example but app will give same result)

**Comment by whghjyh** [comment]
Okay, I understand what happened. I took it upon myself to assume that showly's search function uses tmdb's API (because in the Chinese interface, the information source of the series and movies seems to come from tmdb).
Finally, thank you for your efforts on showly.👍

**Comment by michaldrabik** [comment]
I would be eager to combine them in search but the problem is that tmdb results do not include trakt id so for each and every single element a lookup endpoint from Trakt API would need to be called which is not optimal.
