### ISSUE TITLE
Utilise Trakt's new Additional Site Ratings instead of Metascore + Rotten Tomatoes links

### ISSUE THREAD

**Issue by Victor239** [michaldrabik/showly-2.0#834]
**Describe the bug**
Trakt made an update [a few days ago](https://releasenotes.trakt.tv/release/nEoCe-july-29-2024) which now can show the rating on IMDB, TMDB, Rotten Tomatoes, and Metacritic for each show/movie. These scores can be utilised instead of the current implementation in Showly which are just links to the site.

**Expected behavior**
Instead of the Metascore and Rotten Tomatoes areas just being links they can now instead have the numerical score displayed prominently. It also makes sense to have both types of RT scores - Tomatometer and Audience Score. 

**Screenshots**
![](https://i.imgur.com/7D2UHvO.jpeg)

**Comment by michaldrabik** [comment]
Correct but it is an update for website only. They are not available via the API for apps to use. At least not yet.
