### ISSUE TITLE
Shows added with the "Add to my Shows" button do not sync to Trakt

### ISSUE THREAD

**Issue by berkayfeci** [michaldrabik/showly-2.0#846]
**Describe the bug**
Shows that are added with the "Add to my Shows" button do not sync to Trakt unless you also add at least one episode to your watch history.

**Expected behavior**
My understanding is that if we press that button, at least one episode, for example the first episode, should be added so that it can be synced to Trakt correctly. Otherwise that button should be removed and Watchlist button should be the only button for shows, with the option to add episodes to watched history, instead of adding the show itself as that doesn't work. 

This isn't a problem for movies because "Add to my Movies" button add the movie to watch history as there aren't multiple episodes to consider and they sync fine.

**Comment by michaldrabik** [comment]
It's been like that since the beginning by design so not an issue really. As Showly was originally not intended to be a 1:1 client for Trakt, just use it for syncing. And this was one of the things that I missed in Trakt so it was decided to have that option despite the fact that 0 episodes are not possible to sync with Trakt.

**Comment by berkayfeci** [comment]
But I have a lot of shows that I added this way, at least a way to turn all these shows into wishlisted would be nice so that we can sync them. Otherwise if I delete the app I will lose them all. Or a way to export all the data to a file cause only way of exporting now is via Trakt.

**Comment by michaldrabik** [comment]
Additional export options will come in the future :) I think the fastest way now is to just tap and hold items you wish and use move to watchlist from context menu.
