### ISSUE TITLE
Current Performance Issues

### ISSUE THREAD

**Issue by impydave** [michaldrabik/showly-2.0#847]
Long long time user here ☺ but in the last week or so I have an issues everytime I open the app 😔

I can't mark an episode as watched, and then when you go into any individual show the Cast and Season sections are loading, and take around 60 seconds to finish loading. After that time I can then marks as watched and everything syncs ok.

Just hoping there's an issue as nothing has changed my end, same phone/WiFi etc?

Thanks for a great app!

Dave

**Comment by michaldrabik** [comment]
Hey and thanks. So I am not seeing anything like this right new myself. Maybe just some temp. issues with cloudflare etc.
Where are you from?

**Comment by impydave** [comment]
I'm in the UK 👍 seems intermittent so hopefully as you say just a temporary issue here.

**Comment by michaldrabik** [comment]
Give it some time and reopen this issue if it continues ;) Nothing has been changed in the app about that sections at all.
