### ISSUE TITLE
Show `Specials` for a show

### ISSUE THREAD

**Issue by Victor239** [michaldrabik/showly-2.0#868]
e.g. [Attack on Titan](https://trakt.tv/shows/attack-on-titan) has 37 episodes for the Specials season but this isn't visible within Showly.

**Comment by michaldrabik** [comment]
You can enable Special seasons in settings and they will appear in show's details.

**Comment by Victor239** [comment]
Oh thanks, hadn't noticed that. Is there a way to get it to show in the Progress section how many special episodes are left?

**Comment by michaldrabik** [comment]
Not currently. Specials never appeared in Progress.

**Comment by Victor239** [comment]
Ah okay. It would be helpful to enable it on a show-by-show basis in the future. 

I'd want to leave it by default "on" so I'm aware of which shows have specials to watch, then for shows which have loads of specials which are just behind-the-scenes segments (eg Rings of Power) I'd like to be able to turn off specials from progress for it.

**Comment by michaldrabik** [comment]
I think that what happens now If I understand correctly. If you enable specials in Settings they will be ON in details screen but specials are never included in Progress screens. :)

**Comment by Victor239** [comment]
No I mean I'd like their progress to be included by default, but on show-by-show basis be able to exclude them from progress.

**Comment by michaldrabik** [comment]
> No I mean I'd like their progress to be included by default on progress screens, but on show-by-show basis be able to exclude them from progress screens.

Possibly. Something to log for the future change. For now closing this one as original issue was explained.
