### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by LucaLikesPizza123** [michaldrabik/showly-2.0#874]
Hello, dear Showly team,
I found a bug in the statistics menu. When you click on "show more," the search button is triggered, even though it shouldn’t be there at that moment. I hope this helps, and thank you in advance for fixing it.

https://github.com/user-attachments/assets/c1ff60e0-fe3c-494c-a96e-d31df2ec89a1

**Comment by michaldrabik** [comment]
Thanks I will look into that and issue an update.

**Comment by michaldrabik** [comment]
Issuing quickfix now for version 3.40.1
