### ISSUE TITLE
Unable to install v.30.4.1

### ISSUE THREAD

**Issue by acress1** [michaldrabik/showly-2.0#876]
Hi,

I usually do my updates with Obtainium (Showly via Github), and the last update v3.40.1 doesn't want to install itself. The download is full and then the version stays at 3.40.0.

I also tried to force the update via Github directly, downloading the APK myself, but still.

Thanks,
Regards
Cress

**Comment by michaldrabik** [comment]
@acress1 Oops. I think I just forgot to update the version name string. Meaning if you have a version with code 825 installed this is the correct latest one.

**Comment by acress1** [comment]
@michaldrabik yes indeed, code is 825. ;)
