### ISSUE TITLE
App version not updated in the app

### ISSUE THREAD

**Issue by TentakillLIVE** [michaldrabik/showly-2.0#877]
**Describe the bug**
The version listed in the app does not match the GitHub version. This causes issues for apps like Obtainium because it keeps detecting that the version of the app that is installed is not up-to-date.

**Expected behavior**
Version in app matches GitHub version

**Screenshots**
![Screenshot_20241017-135457](https://github.com/user-attachments/assets/0645b75a-81df-4c98-bae9-3aaef0427f34)

**Comment by michaldrabik** [comment]
Same as #876 
Just a string version bug.
