### ISSUE TITLE
 App Language Translation - German

### ISSUE THREAD

**Issue by michaldrabik** [michaldrabik/showly-2.0#99]
Help needed with translating app's strings into **German**. When completed German language will be added into the app and released.

**Transifex** platform is being used to manage all the translations.

For anyone interested in helping, please visit:

https://www.transifex.com/showly-20/showly-20-android-app 

Click "Help Translate..." to request an invite and become a collaborator.

Some tips:
- in case of any doubts about the context of the string don't hesitate to leave a comment
- let's try to keep translated strings length as close to original English as possible
- all special characters like HTML tags (\<i\>, \<b\> etc.) and new line (\n) should remain as in the original string

**Comment by DurchEins** [comment]
Done. Translation complete. :)

**Comment by michaldrabik** [comment]
@DurchEins Wow thanks! I'll review and check if everything works fine with current UI and let you know If there are any problems

**Comment by DurchEins** [comment]
All right. Feel free to write me. :)

**Comment by michaldrabik** [comment]
@DurchEins 
Added 2 comments in Transifex. Check notifications :)

**Comment by michaldrabik** [comment]
Hi @DurchEins If you have a moment, below you can find an APK for the DE translation update. Please take a quick look and check if everything makes sense. I've made some tiny translations adjustments here and there to fit the UI.

Password to the file is your Transifex nickname (the one starting with "k")

[app-release-de.zip](https://github.com/michaldrabik/showly-2.0/files/5568222/app-release-de.zip)

**Comment by DurchEins** [comment]
> Hi @DurchEins If you have a moment, below you can find an APK for the DE translation update. Please take a quick look and check if everything makes sense. I've made some tiny translations adjustments here and there to fit the UI.
> 
> Password to the file is your Transifex nickname (the one starting with "k")
> 
> [app-release-de.zip](https://github.com/michaldrabik/showly-2.0/files/5568222/app-release-de.zip)

I looked over it. Looks okay so far :)

**Comment by michaldrabik** [comment]
Cool thanks.

**Comment by DurchEins** [comment]
I found a few "bugs" and changed them in Transfix. :)

**Comment by michaldrabik** [comment]
@DurchEins Thanks, are these added as suggestions? Can't see any notifications about it.

**Comment by DurchEins** [comment]
@michaldrabik Yes. The "Save" button was grayed out on my smartphone .Unfortunately, I was only able to submit it as a suggestion. Maybe I did something wrong? 🤔

**Comment by michaldrabik** [comment]
@DurchEins I think it's just Transifex fault. And the save button might be greyed out because its "Reviewed".
If you want to propose a change you I think you should add a suggestion and mention me in comments. Then Transifex will send a notification

**Comment by michaldrabik** [comment]
@DurchEins There is a small amount of new strings and changes considering Movies support I'm working on. Would you mind taking a look in Transifex when you have a chance? Thanks

**Comment by DurchEins** [comment]
@michaldrabik Give me a few more minutes. I'll be done with the translation in a moment. :)
